id: closet_light_off
alias: Turn off the Closet Light
trigger:
  # Door Close
  - entity_id: binary_sensor.door_window_sensor_158d0001b7bb38
    platform: state
    to: 'off'
  # No Motion for 30 seconds
  - entity_id: binary_sensor.motion_sensor_158d0001e51317
    platform: state
    to: 'off'
    for:
      seconds: 30
  # No Motion for 2 minutes
  - entity_id: binary_sensor.motion_sensor_158d0001e51317
    platform: state
    to: 'off'
    for:
      minutes: 2
  # Door Open for 2 minutes
  - entity_id: binary_sensor.door_window_sensor_158d0001b7bb38
    platform: state
    to: 'on'
    for:
      minutes: 2
action:
  - service: light.turn_off
    entity_id: light.closet
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        # Door Closed
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0001b7bb38
        state: 'off'
      # Door Open for 2 minutes
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0001b7bb38
        state: 'on'
        for:
          minutes: 2
    - condition:
      conditions:
      # No Motion for 30 seconds
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d0001e51317
        state: 'off'
        for:
          seconds: 30
