language: python
python:
  - "3.6.3"
install:
  - bash tests/travis_install.sh
script:
  - hass -c . --script check_config
before_install:
  - mv tests/travis_secrets.yaml secrets.yaml

addons:
  apt:
    update: true
    packages:
      - python-dev
      - pkg-config
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libswscale-dev
      - libavresample-dev
      - libavfilter-dev

cache:
  directories:
    - $HOME/.cache/pip
