- id: '1641371956033'
  alias: Hallway Light Switch Scene Controls
  description: Utilizes a blueprint to handle Scene Controls in the Living Room.
  use_blueprint:
    path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
    input:
      zwave_device: 88136be71050b07599ec3caf5928e7a5
      button_a2:
      - service: light.turn_on
        target:
          entity_id: light.kitchen_cabinet_lights
        data:
          brightness_pct: 100
      button_b2:
      - service: light.turn_off
        target:
          entity_id: light.kitchen_cabinet_lights
- id: '1643337826040'
  alias: Living Room Scene Controls
  description: ''
  use_blueprint:
    path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
    input:
      zooz_switch: 4418d1607160e581af11597ef65ef295
      scene_5: []
      scene_1:
      - service: light.toggle
        target:
          entity_id: light.dining_room_lights
      scene_2:
      - service: light.toggle
        target:
          entity_id: light.dining_room_accent_lights
      scene_3h: []
      scene_4:
      - service: light.toggle
        target:
          entity_id: light.kitchen_cabinet_lights
      scene_3:
      - service: light.toggle
        target:
          entity_id: light.kitchen_lights
- id: '1643339651442'
  alias: Living Room Scene Controller Status Lights
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: light.dining_room_lights
  - platform: state
    entity_id: light.dining_room_accent_lights
  - platform: state
    entity_id: light.kitchen_lights
  - platform: state
    entity_id: light.kitchen_cabinet_lights
  condition: []
  action:
  - service: zwave_js.set_value
    target:
      device_id: 4418d1607160e581af11597ef65ef295
    data:
      command_class: '135'
      value: '{{ is_state(''light.dining_room_lights'', ''on'') }}

        '
      property: 68-2
      endpoint: '0'
  - service: zwave_js.set_value
    target:
      device_id: 4418d1607160e581af11597ef65ef295
    data:
      command_class: '135'
      value: '{{ is_state(''light.dining_room_accent_lights'', ''on'') }}

        '
      property: 69-2
      endpoint: '0'
  - service: zwave_js.set_value
    target:
      device_id: 4418d1607160e581af11597ef65ef295
    data:
      command_class: '135'
      value: '{{ is_state(''light.kitchen_lights'', ''on'') }}

        '
      property: 70-2
      endpoint: '0'
  - service: zwave_js.set_value
    target:
      device_id: 4418d1607160e581af11597ef65ef295
    data:
      command_class: '135'
      value: '{{ is_state(''light.kitchen_cabinet_lights'', ''on'') }}

        '
      property: 71-2
      endpoint: '0'
  mode: single
