- id: '1641371956033'
  alias: Hallway Light Switch Scene Controls
  description: Utilizes a blueprint to handle Scene Controls in the Hallway.
  use_blueprint:
    path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
    input:
      zwave_device: 88136be71050b07599ec3caf5928e7a5
      button_a2:
      - service: light.turn_on
        target:
          entity_id: light.kitchen_cabinet_lights
        data:
          brightness_pct: 100
      button_b2:
      - service: light.turn_off
        target:
          entity_id: light.kitchen_cabinet_lights
