---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant.latitude
  longitude: !secret homeassistant.longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 349
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  external_url: !secret http.base_url
  internal_url: !secret http.base_url
  auth_providers:
    - type: command_line
      command: /usr/local/bin/ldap-auth.sh
      args: ["/usr/local/bin/home-assistant.cfg"]
      meta: true
    - type: trusted_networks
      trusted_networks: !secret homeassistant.auth_providers.trusted_networks
      trusted_users: !secret homeassistant.auth_providers.trusted_users

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Enables configuration UI
config:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  ip_ban_enabled: false
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  db_url: !secret recorder.db_url
  auto_purge: false
  exclude:
    entities:
      - sensor.upstairs_roborock_map
      - sensor.downstairs_roborock_map

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  client_id: !secret mqtt.client_id
  certificate: /etc/ssl/certs/ca-certificates.crt
  protocol: 3.1

xiaomi_aqara:
  interface: !secret xiaomi_aqara.interface
  gateways: !secret xiaomi_aqara.gateways

automation: !include automations.yaml
automation old: !include_dir_list automations
group: !include_dir_named groups

sensor:
  - platform: time_date
    display_options:
      - 'time'

python_script:

spotify:
  client_id: !secret spotify.client_id
  client_secret: !secret spotify.client_secret

spotcast:
  sp_dc: !secret spotcast.sp_dc
  sp_key: !secret spotcast.sp_key

browser_mod:
  disable:
    - light

script: !include scripts.yaml

nest:
  client_id: !secret nest.client_id
  client_secret: !secret nest.client_secret
  project_id: !secret nest.project_id
  subscriber_id: !secret nest.subscriber_id

smartir:
  check_updates: false

# fan:
#   - platform: smartir
#     name: Master Bedroom Fan
#     unique_id: master_bedroom_fan
#     controller_data: remote.master_bedroom_ir_transmitter_remote
#     device_code: 1140

mobile_app:

energy:

my:

zha:
  device_config: !secret zha.device_config
  zigpy_config:
    ota:
      ikea_provider: true

backup:

media_source:
