---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant.latitude
  longitude: !secret homeassistant.longitude
  country: US
  currency: USD
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 349
  # metric for Metric, imperial for Imperial
  unit_system: us_customary
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  external_url: !secret http.base_url
  internal_url: !secret http.base_url
  auth_providers:
    - type: command_line
      command: /usr/local/bin/ldap-auth.sh
      args: ["/usr/local/bin/home-assistant.cfg"]
      meta: true
    - type: trusted_networks
      trusted_networks: !secret homeassistant.auth_providers.trusted_networks
      trusted_users: !secret homeassistant.auth_providers.trusted_users

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace:
  mode: storage
  dashboards:
    my-home:
      mode: yaml
      title: Home
      filename: dashboards/home.yaml
      show_in_sidebar: true
      icon: mdi:home

lovelace_gen:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  ip_ban_enabled: false
  use_x_forwarded_for: true
  trusted_proxies: !secret http.trusted_proxies

recorder:
  db_url: !secret recorder.db_url
  auto_purge: false
  exclude:
    entity_globs:
      - sensor.*_remain_charge
      - sensor.*_remain_discharge
      - sensor.*_remain
      - camera.valetudo_*
    entities:
      - sensor.upstairs_roborock_map
      - sensor.downstairs_roborock_map

mqtt:
  sensor:
    - name: Line 103 Status
      unique_id: af52d391-499c-462b-9af6-588c42ddd4ed-status
      state_topic: sip2mqtt/103
      icon: mdi:bell
      value_template: "{{ value_json.verb }}"

    - name: Line 103 Caller Number
      unique_id: af52d391-499c-462b-9af6-588c42ddd4ed-caller-number
      state_topic: sip2mqtt/103
      icon: mdi:bell
      value_template: '{{ value_json.caller.split(" ")[-1] }}'

    - name: Line 103 Caller Name
      unique_id: af52d391-499c-462b-9af6-588c42ddd4ed-caller-name
      state_topic: sip2mqtt/103
      icon: mdi:bell
      value_template: '{{ value_json.caller.split(" ")[:-1]|join(" ", )}}'

  binary_sensor:
    - name: Front Door Motion Sensor
      state_topic: BlueIris/FrontDoorSd/motion
      unique_id: 749ef54c-b0ad-4118-8906-c820de92bdfc
      device_class: motion

automation: !include automations.yaml
automation old: !include_dir_list automations
group: !include_dir_named groups

sensor:
  - platform: time_date
    display_options:
      - 'time'

python_script:

spotcast:
  sp_dc: !secret spotcast.sp_dc
  sp_key: !secret spotcast.sp_key

script: !include scripts.yaml

ingress:
  musicassistant:
    work_mode: ingress
    ui_mode: toolbar
    url: http://localhost:8095
    title: Music Assistant
    icon: mdi:music
    #    parent: hidden

mqtt_discoverystream:
  base_topic: homeassistant-bitfocus-companion
  publish_attributes: true
  publish_timestamps: false
  publish_discovery: true
  include:
    entities:
      - sensor.office_temperature
      - sensor.office_humidity
      - sensor.office_illuminance
      - sensor.living_room_air_quality_score
      - binary_sensor.office_fan_high
      - binary_sensor.office_fan_medium
      - binary_sensor.office_fan_slow
      - binary_sensor.office_fan_is_off
      - script.set_office_fan_high
      - script.set_office_fan_medium
      - script.set_office_fan_slow
      - script.set_office_fan_off
      - button.standing_desk_preset_1
      - button.standing_desk_preset_2
      - button.standing_desk_preset_3
      - button.standing_desk_preset_4
      - sensor.standing_desk_desk_height
      - script.set_office_lights_25_percent
      - script.set_office_lights_50_percent
      - script.set_office_lights_75_percent
      - script.set_office_lights_100_percent
      - binary_sensor.office_lights_100_percent
      - binary_sensor.office_lights_75_percent
      - binary_sensor.office_lights_50_percent
      - binary_sensor.office_lights_25_percent
      - light.office_play_gradient_tube
      - light.office_shelf_lightstrip
      - light.office_desk_lower_lights
      - switch.unused_plug
      - light.left_key_light
      - light.center_key_light
      - light.office_backlighting
      - light.office_video_lights
      - switch.office_webcam_monitor
      - switch.office_ceiling_mics
      - switch.office_speakers
      - input_boolean.sentinal_headset_enabled

battery_notes:
  hide_battery: true

# smartir:
#   check_updates: false

# fan:
#   - platform: smartir
#     name: Master Bedroom Fan
#     unique_id: master_bedroom_fan
#     controller_data: remote.master_bedroom_ir_transmitter_remote
#     device_code: 1140
