homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant.latitude
  longitude: !secret homeassistant.longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 349
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: command_line
      command: /usr/local/bin/ldap-auth.sh
      args: ["/usr/local/bin/home-assistant.cfg"]
      meta: true

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http.base_url
  ip_ban_enabled: False

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  db_url: !secret recorder.db_url
  purge_interval: 0
  exclude:
    entities:
      - sensor.roborock_map

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: !secret mqtt.broker
  port: !secret mqtt.port
  client_id: !secret mqtt.client_id
  certificate: /etc/ssl/certs/ca-certificates.crt
  protocol: 3.1
  username: !secret mqtt.username
  password: !secret mqtt.password
  discovery: true

xiaomi_aqara:
  interface: !secret xiaomi_aqara.interface
  gateways: !secret xiaomi_aqara.gateways

automation old: !include_dir_list automations
group: !include_dir_named groups

sensor:
  - platform: time_date
    display_options:
      - 'time'

  - platform: badnest

python_script:

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave.network_key
  config_path: /etc/homeassistant/openzwave/config/

badnest:
  issue_token: !secret badnest.issue_token
  cookie: !secret badnest.cookie
  region: us

climate:
  - platform: badnest
    scan_interval: 10