homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant.latitude
  longitude: !secret homeassistant.longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 349
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  themes: !include_dir_named themes

# Enables configuration UI
config:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret http.base_url
  use_x_forwarded_for: True
  trusted_proxies: !secret http.trusted_proxies
  trusted_networks: !secret http.trusted_networks
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  db_url: !secret recorder.db_url
  purge_interval: 0

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: !secret mqtt.broker
  port: !secret mqtt.port
  client_id: !secret mqtt.client_id
  certificate: /etc/ssl/certs/ca-certificates.crt
  protocol: 3.1
  username: !secret mqtt.username
  password: !secret mqtt.password
  discovery: true

hue:
  bridges: !secret hue.bridges

xiaomi_aqara:
  interface: !secret xiaomi_aqara.interface
  gateways: !secret xiaomi_aqara.gateways

lutron_caseta:
  host: !secret lutron_caseta.host
  keyfile: caseta.key
  certfile: caseta.crt
  ca_certs: caseta-bridge.crt


automation old: !include_dir_list automations
group: !include_dir_named groups

sensor:
  - platform: time_date
    display_options:
      - 'time'

python_script:
