id: bathroom_fan_on_humidity
alias: Turn on the Bathroom Fan (Humidity)
trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_relative_humidity
    above: 5
action:
  - service: switch.turn_on
    entity_id: switch.bathroom_fan
  - service: automation.turn_on
    entity_id: automation.turn_off_the_bathroom_fan_humidity
