id: bathroom_fan_off_humidity
alias: Turn off the Bathroom Fan (Humidity)
initial_state: 'off'
trigger:
  - platform: numeric_state
    entity_id: sensor.bathroom_relative_humidity
    below: 5
    for:
      minutes: 2
action:
  - service: switch.turn_off
    entity_id: switch.bathroom_fan
  - service: automation.turn_off
    entity_id: automation.turn_off_the_bathroom_fan_humidity
