id: bathroom_fan_on_humidity
alias: Turn on the Bathroom Fan (Humidity)
trigger:
  - platform: numeric_state
    entity_id: sensor.humidity_158d000228846a
    value_template: '{{ states.sensor.humidity_158d000228846a.state|float - states.sensor.humidity_158d0002249e6f.state|float }}'
    above: 5
action:
  - service: switch.turn_on
    entity_id: switch.bathroom_fan
  - service: automation.turn_on
    entity_id: automation.turn_off_the_bathroom_fan_humidity
