id: alert_when_front_door_unlocked
alias: Alert When Front Door Unlocked
trigger:
  - platform: state
    entity_id: lock.front_door
    from: 'locked'
    to: 'unlocked'
action:
  - service: tts.google_say
    data:
      entity_id: media_player.notifications
      message: 'Alert - The front door is unlocked'
  - service: notify.firebasepush_oneplus_5t
    data:
      message: 'Alert - Front door unlocked'
