id: auto_lock_front_door
alias: Auto Lock Front Door
trigger:
  - platform: state
    entity_id: lock.front_door
    from: 'locked'
    to: 'unlocked'
    for:
      seconds: 10
  - platform: state
    entity_id: binary_sensor.door_window_sensor_158d000200a9da
    to: 'off'
    for:
      seconds: 10
condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d000200a9da
    state: 'off'
  - condition: state
    entity_id: lock.front_door
    state: 'unlocked'
action:
  - service: tts.google_say
    data:
      entity_id: media_player.notifications
      message: 'Automatically locking the front door'
  - service: lock.lock
    data:
      entity_id: lock.front_door
  - service: notify.firebasepush_oneplus_5t
    data:
      message: 'Front door automatically locked'
