id: closet_light_on
alias: Turn on the Closet Light
trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b7bb38
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d0001e51317
    platform: state
    to: 'on'
action:
  - service: light.turn_on
    entity_id: light.closet
