id: update_last_presence_location_upstairs
alias: Update Last Presence Location
trigger:
  - entity_id: group.upstairs_presence_detectors
    platform: state
action:
  - service: input_select.select_option
    entity_id: input_select.last_presence_location
    option: "Upstairs"
