---
blueprint:
  domain: automation
  name: Adaptive Lighting Sleep Mode
  description: |
    Enable Adaptive Lighting Sleep Mode at specific times for lights
    that are triggered by motion detectors.
  input:
    adaptive_lighting_switch:
      name: Adaptive Lighting Switch
      description: List of available Adaptive Lighting Switches
      selector:
        entity:
          filter:
            integration: adaptive_lighting
            domain:
              - switch
    bedtime:
      name: Bedtime
      description: The time to reduce the default brightness.
      selector:
        time:
    wakeup_time:
      name: Wake-up time
      description: The time to increase the default brightness.
      selector:
        time:
  source_url: https://github.com/rohankapoorcom/homeassistant-config/blob/master/blueprints/automation/rohankapoorcom/adaptive-lighting-sleep-mode.yaml
mode: single
max_exceeded: silent
triggers:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - trigger: time
    at: !input bedtime
  - trigger: time
    at: !input wakeup_time
actions:
  - choose:
      - alias: If it's bedtime, set the lights to dim.
        conditions:
          - condition: time
            after: !input bedtime
            before: !input wakeup_time
        sequence:
          - action: switch.turn_on
            target:
              entity_id: !input adaptive_lighting_switch
    default:
      - action: switch.turn_off
        target:
          entity_id: !input adaptive_lighting_switch
