blueprint:
  name: Motion / Humidity Bathroom Fan
  description: Turns on a Bathroom Fan when motion or humidity are detected.
  domain: automation
  source_url: https://github.com/rohankapoorcom/homeassistant-config/blob/master/blueprints/automation/rohankapoorcom/bathroom_fan.yaml
  input:
    motion_entity:
      name: Motion Sensor
      description: List of available motion sensor entitites.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    relative_humidity_entity:
      name: Relative Humidity Sensor
      description: The derived humidity sensor based on a baseline and a sensor in the bathroom.
      selector:
        entity:
          domain: sensor
          device_class: humidity
    bathroom_fan_target:
      name: Bathroom Fan Switch
      description: List of available switch entities.
      selector:
        target:
          entity:
            domain: switch
    relative_humidity_high:
      name: Humidity High Point
      description: The difference in humidity point at which the fan should be activated.
      default: 20
      selector:
        number:
          min: 5
          max: 99
    relative_humidity_low:
      name: Humidity Low Point
      description: The difference in humidity point at which the fan should be deactivated.
      default: 5
      selector:
        number:
          min: 5
          max: 99
    delay_time:
      name: Delay time
      description: Time to leave the fan on after last motion is detected and humidity has returned to normal.
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
  - platform: numeric_state
    entity_id: !input relative_humidity_entity
    above: !input relative_humidity_high

action:
  - service: switch.turn_on
    target: !input bathroom_fan_target
  - wait_for_trigger:
      platform: numeric_state
      entity_id: !input relative_humidity_entity
      below: !input relative_humidity_low
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input delay_time
  - service: switch.turn_off
    target: !input bathroom_fan_target
