# yamllint disable-line rule:line-length
---
blueprint:
  name: Inovelli Blue Series VZM31-SN Switch (Zigbee2MQTT)
  description: Create automations for the Inovelli Blue Series VZM31-SN Switch.
  domain: automation
  input:
    inovelli_switch:
      name: Inovelli Switch
      description: List of available Inovelli VZM31-SN switch.
      selector:
        device:
          integration: mqtt
          manufacturer: Inovelli
          multiple: false
    config_button:
      name: Config Press 1x
      description: Action to run, when the config button is pressed one time.
      default: []
      selector:
        action: {}
    button_a:
      name: Up/On Press 1x
      description: Action to run, when the Up button is pressed one time.
      default: []
      selector:
        action: {}
    button_b:
      name: Down/Off Press 1x
      description: Action to run, when the Down button is pressed one time.
      default: []
      selector:
        action: {}
    config_button2:
      name: Config Press 2x
      description: Action to run, when the config button is pressed two times.
      default: []
      selector:
        action: {}
    button_a2:
      name: Up/On Press 2x
      description: Action to run, when the Up button is pressed two times.
      default: []
      selector:
        action: {}
    button_b2:
      name: Down/Off Press 2x
      description: Action to run, when the Down button is pressed two times.
      default: []
      selector:
        action: {}
    config_button3:
      name: Config Press 3x
      description: Action to run, when the config button is pressed three times.
      default: []
      selector:
        action: {}
    button_a3:
      name: Up/On Press 3x
      description: Action to run, when the up button is pressed three times.
      default: []
      selector:
        action: {}
    button_b3:
      name: Down/Off Press 3x
      description: Action to run, when the Down button is pressed three times.
      default: []
      selector:
        action: {}
    config_button4:
      name: Config Press 4x
      description: Action to run, when the config button is pressed four times.
      default: []
      selector:
        action: {}
    button_a4:
      name: Up/On Press 4x
      description: Action to run, when the Up button is pressed four times.
      default: []
      selector:
        action: {}
    button_b4:
      name: Down/Off Press 4x
      description: Action to run, when the Down button is pressed four times.
      default: []
      selector:
        action: {}
    config_button5:
      name: Config Press 5x
      description: Action to run, when the config button is pressed five times.
      default: []
      selector:
        action: {}
    button_a5:
      name: Up/On Press 5x
      description: Action to run, when the Up button is pressed five times.
      default: []
      selector:
        action: {}
    button_b5:
      name: Down/Off Press 5x
      description: Action to run, when the Down button is pressed five times.
      default: []
      selector:
        action: {}
  source_url: https://github.com/rohankapoorcom/homeassistant-config/blob/master/blueprints/automation/rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
mode: single
max_exceeded: silent
variables:
  device_id: !input 'inovelli_switch'
trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/{{device_attr(device_id, 'name') }}"
action:
  - variables:
      button_id: '{{ trigger.payload_json.action }}'
  - choose:
      - conditions: '{{ button_id == "config_single" }}'
        sequence: !input 'config_button'
      - conditions: '{{ button_id == "up_single" }}'
        sequence: !input 'button_a'
      - conditions: '{{ button_id == "down_single" }}'
        sequence: !input 'button_b'
      - conditions: '{{ button_id == "config_double" }}'
        sequence: !input 'config_button2'
      - conditions: '{{ button_id == "up_double" }}'
        sequence: !input 'button_a2'
      - conditions: '{{ button_id == "down_double" }}'
        sequence: !input 'button_b2'
      - conditions: '{{ button_id == "config_triple" }}'
        sequence: !input 'config_button3'
      - conditions: '{{ button_id == "up_triple" }}'
        sequence: !input 'button_a3'
      - conditions: '{{ button_id == "down_triple" }}'
        sequence: !input 'button_b3'
      - conditions: '{{ button_id == "config_quadruple" }}'
        sequence: !input 'config_button4'
      - conditions: '{{ button_id == "up_quadruple" }}'
        sequence: !input 'button_a4'
      - conditions: '{{ button_id == "down_quadruple" }}'
        sequence: !input 'button_b4'
      - conditions: '{{ button_id == "config_quintuple" }}'
        sequence: !input 'config_button5'
      - conditions: '{{ button_id == "up_quintuple" }}'
        sequence: !input 'button_a5'
      - conditions: '{{ button_id == "down_quintuple" }}'
        sequence: !input 'button_b5'
