---
blueprint:
  name: Inovelli VZW31-SN Lock Notifications
  description: Displays the current status of the lock using an Inovelli Red Series VZW31-SN Dimmer Switch
  domain: automation
  input:
    lock_entity:
      name: Lock Entity
      description: List of available lock entities
      selector:
        entity:
          domain: lock
    zwave_device:
      name: Inovelli Switch
      description: List of available Inovelli VZW31-SN switches.
      selector:
        device:
          integration: zwave_js
          manufacturer: Inovelli
          model: VZW31-SN
  source_url: https://github.com/rohankapoorcom/homeassistant-config/blob/master/blueprints/automation/rohankapoorcom/inovelli-vzw31-sn-red-series-lock-notifications.yaml
mode: single
max_exceeded: silent
triggers:
  - trigger: state
    entity_id: !input lock_entity
actions:
  - action: zwave_js.bulk_set_partial_config_parameters
    target:
      device_id: !input zwave_device
    data_template:
      parameter: 99
      value:
        "All LED Strip Effect - Color": >
          {% if trigger.to_state.state == 'locked' %}
            Green
          {% else %}
            Red
          {% endif %}
        "All LED Strip Effect - Level": 40
        "All LED Strip Effect - Duration": 255
        "All LED Strip Effect - Effect": Solid
