id: chromecast_audio_previous
alias: Rewind Chromecast Audio
trigger:
  - platform: event
    event_type: roku_command
    event_data:
      roku_usn: 4t8k7RAjE3TBcfheQvCATZ
      type: keypress
      key: Rev
action:
  - service: media_player.media_previous_track
    entity_id: media_player.all_speakers
