id: chromecast_audio_skip
alias: Skip Chromecast Audio
trigger:
  - platform: event
    event_type: roku_command
    event_data:
      roku_usn: 4t8k7RAjE3TBcfheQvCATZ
      type: keypress
      key: Fwd
action:
  - service: media_player.media_next_track
    entity_id: media_player.all_speakers
