id: turn_off_speakers_when_chromecast_audio_stops_playing
alias: Turn off Speakers when Chromecast Audio Stops Playing
trigger:
  - entity_id: media_player.all_speakers
    platform: state
    to: 'off'
    for:
      minutes: 10
  - entity_id: media_player.all_speakers
    platform: state
    to: 'paused'
    for:
      minutes: 10
action:
  - service: remote.turn_off
    entity_id: remote.living_room_hub
  - service: remote.turn_off
    entity_id: remote.upstairs_hub
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: media_player.all_speakers
      state: 'off'
    - condition: state
      entity_id: media_player.all_speakers
      state: 'paused'
