###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/29/2018
#  @package      :  Plates Components
#  @description  :  Logic for handling general components shared by the HASP
#                   group 'plates'.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'plates_components'

    automation.hasp_plates_components_BacklightBySun:
      <<: *customize

################################################
## Automation
################################################

automation:
##############################################################################
# Set backlight based on sun elevation according to following:
# elevation > 10 == backlight 255
# elevation -10 to 10 == backlight 20 to 255
# elevation below -10 == backlight 20
  - alias: hasp_plates_components_BacklightBySun
    trigger:
      - platform: time
        # Matches every minute
        seconds: 00
    condition:
      - condition: and
        conditions:
        - condition: template
          value_template: "{{ state_attr('sun.sun', 'elevation') <= 10 }}"
        - condition: template
          value_template: "{{ state_attr('sun.sun', 'elevation') >= -10 }}"
      # Todo add check against all plates being connected
    action:
      - service: mqtt.publish
        data:
          topic: 'hasp/plates/brightness/set'
          payload_template: >
            {% if state_attr('sun.sun', 'elevation') >= 10 %}
              255
            {% elif (state_attr('sun.sun', 'elevation') < 10) and (state_attr('sun.sun', 'elevation') > -10) %}
              {{ ((state_attr('sun.sun', 'elevation') + 10) * 12.5) | int + 5 }}
            {% else %}
              5
            {% endif %}
