###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Plates P8
#  @description  :  Logic for handling Page 8 on the HASP group 'plates'.
#                   Page 8 shows the current media playback on All Speakers
#                   and allows interacting with the sound system.
###############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'plates_p8'

      media_player_entity: &media_player_entity
          entity_id: media_player.all_speakers

      automation.hasp_plates_p8_MediaTitle:
        <<: *customize
      automation.hasp_plates_p8_MediaArtist:
        <<: *customize
      automation.hasp_plates_p8_MediaPlayPause:
        <<: *customize

################################################
## Automation
################################################
automation:

  - alias: hasp_plates_p8_MediaTitle
    trigger:
      - platform: state
        entity_id: sensor.all_speakers_media_title
    action:
      - service: python_script.hasp_update_message
        data_template:
          nodename: plates
          object_id: 'p[8].b[4]'
          text: "{{ states('sensor.all_speakers_media_title')|wordwrap(20, wrapstring='\\r') }}"

  - alias: hasp_plates_p8_MediaArtist
    trigger:
      - platform: state
        entity_id: sensor.all_speakers_media_artist
    action:
      - service: python_script.hasp_update_message
        data_template:
          nodename: plates
          object_id: 'p[8].b[5]'
          text: "{{ states('sensor.all_speakers_media_artist')|wordwrap(20, wrapstring='\\r') }}"

  - alias: hasp_plates_p8_MediaPlayPause
    trigger:
      - platform: state
        <<: *media_player_entity
        to: 'playing'
      - platform: state
        <<: *media_player_entity
        to: 'paused'
      - platform: state
        <<: *media_player_entity
        to: 'off'
    action:
      - service: python_script.hasp_update_message
        data_template:
          nodename: plates
          object_id: 'p[8].b[7]'
          text: >
            {% if is_state('media_player.all_speakers', 'playing') %}
            ;
            {% elif is_state('media_player.all_speakers', 'paused') %}
            4
            {% else %}
            ;
            {% endif %}
          update_font: 'false'
