id: bathroom_sink_lights_off
alias: Turn off Bathroom Sink Lights
trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e05978
    for:
      minutes: 2
    platform: state
    to: 'off'
action:
  - entity_id: switch.sink_lights
    service: switch.turn_off
