id: bathroom_light_on
alias: Turn on the Bathroom Light
trigger:
  # Door closed
  - entity_id: binary_sensor.door_window_sensor_158d0001de6091
    platform: state
    to: 'off'
  # Motion detected
  - entity_id: group.bathroom_motion
    platform: state
    to: 'on'
action:
  - service: switch.turn_on
    entity_id: switch.bathroom_light
