id: dim_lights_roku_play
alias: Dim Lights when Roku Plays
trigger:
  - platform: event
    event_type: roku_command
    event_data:
      roku_usn: 4t8k7RAjE3TBcfheQvCATZ
      type: keypress
      key: DirectionUp
action:
  - service: homeassistant.turn_off
    entity_id: group.downstairs_lights
  - service: homeassistant.turn_on
    entity_id: group.end_tables
    data:
      color_temp: 432
      brightness: 120
condition:
  # Dusk
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ states.sun.sun.attributes.elevation }}'
    below: 2
