id: desk_backlighting_off
alias: Turn off Desk Backlighting
trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e50fb5
    for:
      minutes: 5
    platform: state
    to: 'off'
action:
  - entity_id: light.desk_strip_white
    service: light.turn_off
  - entity_id: light.desk_strip_color
    service: light.turn_off
