id: desk_backlighting_on
alias: Turn on Desk Backlighting
trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e50fb5
    platform: state
    to: 'on'
action:
  - service: light.turn_on
    entity_id: light.desk_strip_white
    data:
      brightness_pct: 100
  - service: light.turn_on
    entity_id: light.desk_strip_color
    data:
      brightness_pct: 100
      color_temp: 233
