###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Up Plate P2
#  @description  :  Handles page 2 on the upstairs HA Wallplate. Page 2 shows
#                   upstairs temperature/humidity. All other functions are
#                   managed by the plates_p2 package.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'up_plate_p2'

    automation.hasp_up_plate_p2_Weather:
      <<: *customize

################################################
## Automation
################################################
automation:
  # Send Temperature/Humidity
  - alias: hasp_up_plate_p2_Weather
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: sensor.temperature_158d0002249e6f
      - platform: state
        entity_id: sensor.humidity_158d0002249e6f
    action:
      - service: python_script.hasp_update_message
        data_template:
          nodename: up_plate
          object_id: 'p[2].b[6]'
          text: "{{states('sensor.temperature_158d0002249e6f')}}F|{{states('sensor.humidity_158d0002249e6f')}}%"
