###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Up Plate P8
#  @description  :  Handles page 8 on the upstairs HA Wallplate. Page 8 shows
#                   the current media playback on All Speakers and allows
#                   interacting with the sound system. Some functionality
#                   provided by the plates_p8 package.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'up_plate_p8'

      media_player_entity: &media_player_entity
          entity_id: media_player.all_speakers

    automation.hasp_up_plate_p8_MediaPauseButton7:
      <<: *customize
    automation.hasp_up_plate_p8_MediaPrevTrackButton6:
      <<: *customize
    automation.hasp_up_plate_p8_MediaNextTrackButton8:
      <<: *customize
    automation.hasp_up_plate_p8_MediaVolSliderUpdateHass:
      <<: *customize

################################################
## Automation
################################################
automation:

  # Play/Pause button action
  - alias: hasp_up_plate_p8_MediaPauseButton7
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[8].b[7]'
        payload: 'ON'
    action:
      - service: media_player.media_play_pause
        <<: *media_player_entity

  # Prev Track button action
  - alias: hasp_up_plate_p8_MediaPrevTrackButton6
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[8].b[6]'
        payload: 'ON'
    action:
      - service: media_player.media_previous_track
        <<: *media_player_entity

  # Next Track button action
  - alias: hasp_up_plate_p8_MediaNextTrackButton8
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[8].b[8]'
        payload: 'ON'
    action:
      - service: media_player.media_next_track
        <<: *media_player_entity

  # Volume slider value published, apply published state
  - alias: hasp_up_plate_p8_MediaVolSliderUpdateHass
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[8].b[9].val'
    action:
      - service: script.harmony_volume
        data_template:
          increment: "{{ (states('input_number.volume_increment'))|int }}"
          entity_id: remote.upstairs_hub
          vol_up: >
            {% if trigger.payload|int > 50 %}
              true
            {% elif trigger.payload|int < 50 %}
              false
            {% endif %}
      - service: mqtt.publish
        data:
          topic: 'hasp/up_plate/command/p[8].b[9].val'
          payload: 50
