##############################################################################
# The devices created below are essential to the page control automations
# and you'll probably want to carry them over to your own configuration
homeassistant:
  customize:
    input_number.hasp_up_plate_alarmcode1:
      hidden: true
    input_number.hasp_up_plate_alarmcode2:
      hidden: true
    input_number.hasp_up_plate_alarmcode3:
      hidden: true
    input_number.hasp_up_plate_alarmcode4:
      hidden: true

light:
  - platform: mqtt
    name: up_plate Backlight
    command_topic: "hasp/up_plate/light/switch"
    state_topic: "hasp/up_plate/light/status"
    brightness_state_topic: "hasp/up_plate/brightness/status"
    brightness_command_topic: "hasp/up_plate/brightness/set"
    retain: true

binary_sensor:
  - platform: mqtt
    name: up_plate Connected
    device_class: connectivity
    state_topic: "hasp/up_plate/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/up_plate/status"
    payload_available: "ON"
    payload_not_available: "OFF"

sensor:
  - platform: mqtt
    name: up_plate Sensor
    state_topic: "hasp/up_plate/sensor"
    value_template: '{{ value_json.status }}'
    json_attributes_topic: "hasp/up_plate/sensor"

input_text:
  hasp_up_plate_pagebutton1label:
    name: up_plate Page 1 Label
    icon: mdi:book-open-page-variant
  hasp_up_plate_pagebutton2label:
    name: up_plate Page 2 Label
    icon: mdi:book-open-page-variant
  hasp_up_plate_pagebutton3label:
    name: up_plate Page 3 Label
    icon: mdi:book-open-page-variant

input_number:
  hasp_up_plate_pagebutton1page:
    name: up_plate Page 1 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_up_plate_pagebutton2page:
    name: up_plate Page 2 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_up_plate_pagebutton3page:
    name: up_plate Page 3 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_up_plate_activepage:
    name: up_plate Active Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_up_plate_alarmcode1:
    name: up_plate AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_up_plate_alarmcode2:
    name: up_plate AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_up_plate_alarmcode3:
    name: up_plate AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_up_plate_alarmcode4:
    name: up_plate AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

automation:
##############################################################################
# Set default values for input_text/number sliders
  - alias: hasp_up_plate_00_FirstTimeSetup
    trigger: []
    action:
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_up_plate_pagebutton1label'
          value: 'scenes'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_up_plate_pagebutton2label'
          value: 'status'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_up_plate_pagebutton3label'
          value: 'lights'
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_up_plate_pagebutton1page'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_up_plate_pagebutton2page'
          value: 2
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_up_plate_pagebutton3page'
          value: 3
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_up_plate_activepage'
          value: 1
