###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Up Plate P3
#  @description  :  Handles page 3 on the upstairs HA Wallplate. Page 3 is
#                   the first page of lighting controls.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'up_plate_p3'

    automation.hasp_up_plate_p3_ToggleInit:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleEndTables:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleCouchAccent:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleTVBacklight:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleCornerLight:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleColor1:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleColor2:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleColor3:
      <<: *customize
    automation.hasp_up_plate_p3_ToggleColor4:
      <<: *customize

################################################
## Automation
################################################
automation:
  # Set font and text for toggle buttons on device connection
  - alias: hasp_up_plate_p3_ToggleInit
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/status'
        payload: 'ON'
    action:
      - service: python_script.hasp_update_message
        data:
          nodename: up_plate
          object_id: 'p[3].b[4]'
          text: 'Couch Tables'
      - service: python_script.hasp_update_message
        data:
          nodename: up_plate
          object_id: 'p[3].b[5]'
          text: 'Couch Accent'
      - service: python_script.hasp_update_message
        data:
          nodename: up_plate
          object_id: 'p[3].b[6]'
          text: 'TV Backlight'
      - service: python_script.hasp_update_message
        data:
          nodename: up_plate
          object_id: 'p[3].b[7]'
          text: 'Corner Light'

  - alias: hasp_up_plate_p3_ToggleEndTables
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[3].b[4]'
        payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: group.end_tables

  - alias: hasp_up_plate_p3_ToggleCouchAccent
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[3].b[5]'
        payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: light.couch_accent_white

  - alias: hasp_up_plate_p3_ToggleTVBacklight
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[3].b[6]'
        payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: light.tv_backlight_color

  - alias: hasp_up_plate_p3_ToggleCornerLight
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/state/p[3].b[7]'
        payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: light.living_room_lamp

  - alias: hasp_up_plate_p3_ToggleColor1
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: group.end_tables
    action:
      - service: mqtt.publish
        data_template:
          topic: 'hasp/up_plate/command/p[3].b[4].bco'
          payload_template: >-
            {% if is_state('group.end_tables', 'on') -%}
              64577
            {%- else -%}
              25388
            {%- endif %}
      - service: mqtt.publish
        data_template:
          topic: 'hasp/up_plate/command/p[3].b[4].pco'
          payload_template: >-
            {% if is_state('group.end_tables', 'on') -%}
              0
            {%- else -%}
              65535
            {%- endif %}

  - alias: hasp_up_plate_p3_ToggleColor2
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: light.couch_accent_white
    action:
      - service: mqtt.publish
        data:
          topic: 'hasp/up_plate/command/p[3].b[5].bco'
          payload_template: >-
            {% if is_state('light.couch_accent_white', 'on') -%}
              64577
            {%- else -%}
              25388
            {%- endif %}
      - service: mqtt.publish
        data_template:
          topic: 'hasp/up_plate/command/p[3].b[5].pco'
          payload_template: >-
            {% if is_state('light.couch_accent_white', 'on') -%}
              0
            {%- else -%}
              65535
            {%- endif %}

  - alias: hasp_up_plate_p3_ToggleColor3
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: light.tv_backlight_color
    action:
      - service: mqtt.publish
        data:
          topic: 'hasp/up_plate/command/p[3].b[6].bco'
          payload_template: >-
            {% if is_state('light.tv_backlight_color', 'on') -%}
              64577
            {%- else -%}
              25388
            {%- endif %}
      - service: mqtt.publish
        data_template:
          topic: 'hasp/up_plate/command/p[3].b[6].pco'
          payload_template: >-
            {% if is_state('light.tv_backlight_color', 'on') -%}
              0
            {%- else -%}
              65535
            {%- endif %}

  - alias: hasp_up_plate_p3_ToggleColor4
    trigger:
      - platform: mqtt
        topic: 'hasp/up_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: light.living_room_lamp
    action:
      - service: mqtt.publish
        data:
          topic: 'hasp/up_plate/command/p[3].b[7].bco'
          payload_template: >-
            {% if is_state('light.living_room_lamp', 'on') -%}
              64577
            {%- else -%}
              25388
            {%- endif %}
      - service: mqtt.publish
        data_template:
          topic: 'hasp/up_plate/command/p[3].b[7].pco'
          payload_template: >-
            {% if is_state('light.living_room_lamp', 'on') -%}
              0
            {%- else -%}
              65535
            {%- endif %}
