###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  01/31/2022
#  @package      :  Living Room / Lights
#  @description  :  Integrates lighting controls in the living room
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'living_room_lights'

################################################
## Automation
################################################
automation:
  - id: '1643337826040'
    alias: Living Room Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Living Room.
    use_blueprint:
      path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
      input:
        zooz_switch: 4418d1607160e581af11597ef65ef295
        scene_1:
          - service: light.toggle
            target:
              entity_id: light.dining_room_lights
        scene_2:
          - service: light.toggle
            target:
              entity_id: light.dining_room_accent_lights
        scene_4:
          - service: light.toggle
            target:
              entity_id: light.kitchen_cabinet_lights
        scene_3:
          - service: light.toggle
            target:
              entity_id: light.kitchen_lights

  - id: '1643339651442'
    alias: Living Room Scene Controller Status Lights
    description: 'Utilizes a blueprint to map track lighting states on the Scene Controller in the Living Room.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controller-status-lights.yaml
      input:
        zooz_switch: 4418d1607160e581af11597ef65ef295
        small_1_button_light: light.dining_room_lights
        small_2_button_light: light.dining_room_accent_lights
        small_3_button_light: light.kitchen_lights
        small_4_button_light: light.kitchen_cabinet_lights
