###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  01/31/2022
#  @package      :  Living Room / Lights
#  @description  :  Integrates lighting controls in the living room
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'living_room_lights'

    living_room_light_switch_device_id: &living_room_light_switch_device_id
      - 257a7b48517ba7c9cc28fa70842c24f6

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      living_room_fan_slow:
        friendly_name: Living Room Fan Set to Slow
        value_template: >
          {{ state_attr('fan.living_room_fan', 'percentage') > 0
          and state_attr('fan.living_room_fan', 'percentage') <= 52 }}

      living_room_fan_medium:
        friendly_name: Living Room Fan Set to Medium
        value_template: >
          {{ state_attr('fan.living_room_fan', 'percentage') > 52
          and state_attr('fan.living_room_fan', 'percentage') <= 81 }}

      living_room_fan_high:
        friendly_name: Living Room Fan Set to High
        value_template: "{{ state_attr('fan.living_room_fan', 'percentage') > 81 }}"

      living_room_fan_off:
        friendly_name: Living Room Fan Set to High
        value_template: "{{ is_state('fan.living_room_fan', 'off') }}"

################################################
## Automation
################################################
automation:
  - id: '8fbfa021-9205-4f56-b3a0-9eea04900c42'
    alias: Living Room Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Living Room.
    use_blueprint:
      path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
      input:
        zooz_switch: f5f0fa81fd632379a87e70da0c55057f
        scene_1:
          - service: fan.turn_on
            target:
              entity_id: fan.living_room_fan
            data:
              percentage: 100
        scene_2:
          - service: fan.turn_on
            target:
              entity_id: fan.living_room_fan
            data:
              percentage: 65
        scene_4:
          - service: fan.turn_off
            target:
              entity_id: fan.living_room_fan
        scene_3:
          - service: fan.turn_on
            target:
              entity_id: fan.living_room_fan
            data:
              percentage: 27

  - id: '38a41f0a-5b07-4efc-804c-3e19fadc156b'
    alias: Living Room Scene Controller Status Lights
    description: 'Utilizes a blueprint to map track lighting states on the Scene Controller in the Living Room.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controller-status-lights.yaml
      input:
        zooz_switch: f5f0fa81fd632379a87e70da0c55057f
        large_button_light: light.living_room_lights
        small_1_button_light: binary_sensor.living_room_fan_high
        small_2_button_light: binary_sensor.living_room_fan_medium
        small_3_button_light: binary_sensor.living_room_fan_slow
        small_4_button_light: binary_sensor.living_room_fan_off

  - id: '023bc818-9231-4450-b15b-1dc7692f3fbb'
    alias: Living Room Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Living Room.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-switch.yaml
      input:
        zwave_device:
          *living_room_light_switch_device_id
        config_button:
          - service: cover.toggle
            data: {}
            target:
              entity_id: cover.living_room_curtains
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *living_room_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close
        button_a2:
          - service: cover.open_cover
            data: {}
            target:
              entity_id: cover.living_room_sheers
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *living_room_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close
        button_b2:
          - service: cover.close_cover
            data: {}
            target:
              entity_id: cover.living_room_sheers
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *living_room_light_switch_device_id
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 40
                All LED Strip Effect - Duration: 10
                All LED Strip Effect - Effect: Open/close
