###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/30/2018
#  @package      :  Media / TV
#  @description  :  Integrates lighting and the Harmony Remote for TV/Movies
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'media_tv'

################################################
## Automation
################################################
automation:
  - id: faea6bc6-9c9b-439c-9f5a-ac65fbec8cdf
    alias: Handle Shield Emulated Roku Harmony Commands
    description: Executed commands on the Living Room Shield TV in response to Emulated Roku events from the Harmony Hub
    use_blueprint:
      path: rohankapoorcom/emulated-roku.yaml
      input:
        emulated_roku_name: 4t8k7RAjE3TBcfheQvCATZ
        up_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: Netflix
        right_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: Plex
        down_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: YouTube
        left_action:
          - service: androidtv.adb_command
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              # yamllint disable-line rule:line-length
              command: "am start -a android.intent.action.VIEW -d -n com.amazon.amazonvideo.livingroom/com.amazon.ignition.IgnitionActivity"
        home_action:
          - service: media_player.select_source
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              source: "com.hbo.hbonow"
        search_action:
          - service: androidtv.adb_command
            target:
              entity_id: media_player.living_room_shield_tv
            data:
              command: SEARCH

  - id: c8ff656a-e0d6-4b26-9840-0da9863b1867
    alias: Living Room Shield TV Notify Washer
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_wash_completed
        to: 'on'
    action:
      - service: notify.living_room_shield_tv
        data:
          title: Washer Complete
          message: The washer has finished it's cycle.
          data:
            duration: 10
            position: top-right
            transparency: 50%

  - id: e2f38056-ce90-46ca-8138-51a9637e3e50
    alias: Living Room Shield TV Notify Dryer
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_dry_completed
        to: 'on'
    action:
      - service: notify.living_room_shield_tv
        data:
          title: Dryer Complete
          message: The dryer has finished it's cycle.
          data:
            duration: 10
            position: top-right
            transparency: 50%

  - id: c34228e0-c6c9-431f-ad73-cef94537ca2c
    alias: Living Room TV Notify Phone Call
    trigger:
      - platform: state
        entity_id: sensor.line_103_status
        to: 'incoming'
    action:
      - service: notify.living_room_shield_tv
        data_template:
          title: Incoming Phone Call
          message: >
            {{ states('sensor.line_103_caller_name')}} - {{states('sensor.line_103_caller_number') }}
          data:
            duration: 25
            position: top-right
            transparency: 50%

  - id: 6ed8bef7-8ed6-4278-b79f-fefa9bf2ab8b
    alias: Control the Living Room TV Remote when Charging
    description: Turn off the motion detection and screen when the Living Room TV Remote is charging.
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id: binary_sensor.living_room_tv_remote_plugged_in
    action:
      - choose:
          - alias: If the Living Room TV Remote is charging, turn off the motion detection and screen
            conditions:
              - condition: state
                entity_id: binary_sensor.living_room_tv_remote_plugged_in
                state: 'on'
            sequence:
              - service: switch.turn_off
                entity_id: switch.living_room_tv_remote_motion_detection
              - service: light.turn_off
                entity_id: light.living_room_tv_remote_screen
        default:
          - service: switch.turn_on
            entity_id: switch.living_room_tv_remote_motion_detection
          - service: light.turn_on
            entity_id: light.living_room_tv_remote_screen

################################################
## Script
################################################
script:
  turn_on_watch_living_room_tv:
    alias: Turn on the Living Room TV
    sequence:
      - service: media_player.turn_on
        target:
          device_id:
            - ef1d3c8a3b4dd25bd2df119af1e26994
            - 404bd26637ee4f98939fc2fc8552398f
            - 556fadd7ebff47319b8eaf65a20b6804
      - service: denonavr.get_command
        target:
          device_id: 404bd26637ee4f98939fc2fc8552398f
        data:
          command: /goform/formiPhoneAppDirect.xml?MSQUICK1
      - service: androidtv.adb_command
        data:
          entity_id: media_player.living_room_shield_tv
          command: HOME
      - service: switch.turn_off
        target:
          entity_id: switch.living_room_conference_camera
    mode: single
    icon: mdi:television

  turn_off_the_living_room_tv:
    alias: Turn off the Living Room TV
    sequence:
      - service: media_player.turn_off
        target:
          device_id:
            - ef1d3c8a3b4dd25bd2df119af1e26994
            - 404bd26637ee4f98939fc2fc8552398f
            - 556fadd7ebff47319b8eaf65a20b6804
      - service: switch.turn_off
        target:
          entity_id: switch.living_room_conference_camera
    mode: single
    icon: mdi:television-off

  turn_on_the_living_room_speakers:
    alias: Turn on the Living Room Speakers
    sequence:
      - service: media_player.turn_on
        target:
          device_id:
            - 404bd26637ee4f98939fc2fc8552398f
      - service: media_player.turn_off
        target:
          device_id:
            - ef1d3c8a3b4dd25bd2df119af1e26994
            - 556fadd7ebff47319b8eaf65a20b6804
      - service: denonavr.get_command
        target:
          device_id: 404bd26637ee4f98939fc2fc8552398f
        data:
          command: /goform/formiPhoneAppDirect.xml?MSQUICK4
    mode: single
    icon: mdi:speaker

  turn_on_the_nintendo_switch:
    alias: Turn on the Nintendo Switch
    sequence:
      - service: media_player.turn_on
        target:
          device_id:
            - ef1d3c8a3b4dd25bd2df119af1e26994
            - 404bd26637ee4f98939fc2fc8552398f
            - 556fadd7ebff47319b8eaf65a20b6804
      - service: denonavr.get_command
        target:
          device_id: 404bd26637ee4f98939fc2fc8552398f
        data:
          command: /goform/formiPhoneAppDirect.xml?MSQUICK2
    mode: single
    icon: mdi:nintendo-switch

  turn_on_the_living_room_video_conferencing_system:
    alias: Turn on the Living Room Video Conferencing System
    sequence:
      - service: media_player.turn_on
        target:
          device_id:
            - ef1d3c8a3b4dd25bd2df119af1e26994
            - 404bd26637ee4f98939fc2fc8552398f
      - service: switch.turn_on
        target:
          entity_id: switch.living_room_conference_camera
      - service: media_player.select_source
        target:
          device_id: ab65d3019b2049668b610bf0c5bc58c2
        data:
          source: HDMI-1
      - service: denonavr.get_command
        target:
          device_id: 404bd26637ee4f98939fc2fc8552398f
        data:
          command: /goform/formiPhoneAppDirect.xml?MSQUICK3
    mode: single
    icon: mdi:video
