###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Down Plate P9
#  @description  :  Handles page 9 on the downstairs HA Wallplate. Page 9 is
#                   the second page of lighting controls.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'down_plate_p9'

    automation.hasp_down_plate_p9_ToggleInit:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleEndTables:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleCouchAccent:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleTVBacklight:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleCornerLight:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleColor1:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleColor2:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleColor3:
      <<: *customize
    automation.hasp_down_plate_p9_ToggleColor4:
      <<: *customize

################################################
## Automation
################################################
automation:
  # Set font and text for toggle buttons on device connection
  - alias: hasp_down_plate_p9_ToggleInit
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/status'
        payload: 'ON'
    action:
      - service: python_script.hasp_update_message
        data:
          nodename: down_plate
          object_id: 'p[9].b[4]'
          text: 'Kitchen Table'
      - service: python_script.hasp_update_message
        data:
          nodename: down_plate
          object_id: 'p[9].b[5]'
          text: 'Kitchen Sink'
      - service: python_script.hasp_update_message
        data:
          nodename: down_plate
          object_id: 'p[9].b[6]'
          text: 'Server Rack'
      - service: python_script.hasp_update_message
        data:
          nodename: down_plate
          object_id: 'p[9].b[7]'
          text: ''

  - alias: hasp_down_plate_p9_ToggleKitchenTable
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/state/p[9].b[4]'
        payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: light.kitchen_table

  - alias: hasp_down_plate_p9_ToggleKitchenSink
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/state/p[9].b[5]'
        payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: light.kitchen_sink_light

  - alias: hasp_down_plate_p9_ToggleServerRack
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/state/p[9].b[6]'
        payload: 'ON'
    action:
      - service: homeassistant.toggle
        entity_id: switch.server_rack_lights

  - alias: hasp_down_plate_p9_ToggleColor1
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: light.kitchen_table
    action:
      - service: python_script.hasp_update_colors
        data_template:
          nodename: down_plate
          object_id: 'p[9].b[4]'
          background: >-
            {% if is_state('light.kitchen_table', 'on') -%}
              64577
            {%- else -%}
              25388
            {%- endif %}
          foreground: >-
            {% if is_state('light.kitchen_table', 'on') -%}
              0
            {%- else -%}
              65535
            {%- endif %}

  - alias: hasp_down_plate_p9_ToggleColor2
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: light.kitchen_sink_light
    action:
      - service: python_script.hasp_update_colors
        data_template:
          nodename: down_plate
          object_id: 'p[9].b[5]'
          background: >-
            {% if is_state('light.kitchen_sink_light', 'on') -%}
              64577
            {%- else -%}
              25388
            {%- endif %}
          foreground: >-
            {% if is_state('light.kitchen_sink_light', 'on') -%}
              0
            {%- else -%}
              65535
            {%- endif %}

  - alias: hasp_down_plate_p9_ToggleColor3
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/status'
        payload: 'ON'
      - platform: state
        entity_id: switch.server_rack_lights
    action:
      - service: python_script.hasp_update_colors
        data_template:
          nodename: down_plate
          object_id: 'p[9].b[6]'
          background: >-
            {% if is_state('switch.server_rack_lights', 'on') -%}
              64577
            {%- else -%}
              25388
            {%- endif %}
          foreground: >-
            {% if is_state('switch.server_rack_lights', 'on') -%}
              0
            {%- else -%}
              65535
            {%- endif %}
