##############################################################################
# Automations for handling Scene select buttons on page 1

automation:
  # Set font and text labels for scene buttons on device connection
  - alias: hasp_down_plate_p1_ScenesInit
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[4].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[4].txt'
        payload: '"All Lights On"'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[5].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[5].txt'
        payload: '"Living Room"'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[6].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[6].txt'
        payload: '"Kitchen"'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[7].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[1].b[7].txt'
        payload: '"All Lights Off"'

  # Trigger scene.downstairs_lights_on when p[1].b[4] pressed
  - alias: hasp_down_plate_p1_SceneButton4
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[4]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.downstairs_lights_on

  # Trigger scene.living_room_lights_on when p[1].b[5] pressed
  - alias: hasp_down_plate_p1_SceneButton5
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[5]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.living_room_lights_on

  # Trigger scene.kitchen_lights_on when p[1].b[6] pressed
  - alias: hasp_down_plate_p1_SceneButton6
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[6]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.kitchen_lights_on

  # Trigger scene.downstairs_lights_off when p[1].b[7] pressed
  - alias: hasp_down_plate_p1_SceneButton7
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[7]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.downstairs_lights_off
