###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/23/2018
#  @package      :  Down Plate P8
#  @description  :  Handles page 8 on the downstairs HA Wallplate. Page 8 shows
#                   the current media playback on All Speakers and always
#                   interacting with the sound system.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'down_plate_p8'

      media_player_entity: &media_player_entity
          entity_id: media_player.all_speakers

    automation.hasp_down_plate_p8_MediaInit:
      <<: *customize
    automation.hasp_down_plate_p8_MediaPauseButton7:
      <<: *customize
    automation.hasp_down_plate_p8_MediaPrevTrackButton6:
      <<: *customize
    automation.hasp_down_plate_p8_MediaNextTrackButton8:
      <<: *customize
    automation.hasp_down_plate_p8_MediaTitle:
      <<: *customize
    automation.hasp_down_plate_p8_MediaArtist:
      <<: *customize
    automation.hasp_down_plate_p8_MediaPlayPause:
      <<: *customize
    automation.hasp_down_plate_p8_MediaVolSliderUpdateHass:
      <<: *customize

################################################
## Automation
################################################
automation:
# Initialize button text/font for media controls on start
  - alias: hasp_down_plate_p8_MediaInit
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[8].b[6].font'
        payload: '4'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[8].b[7].font'
        payload: '4'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[8].b[8].font'
        payload: '4'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[8].b[6].txt'
        payload: '"9"'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[8].b[7].txt'
        payload: '";"'
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[8].b[8].txt'
        payload: '":"'

  # Play/Pause button action
  - alias: hasp_down_plate_p8_MediaPauseButton7
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[8].b[7]'
      payload: 'ON'
    action:
      service: media_player.media_play_pause
      <<: *media_player_entity

  # Prev Track button action
  - alias: hasp_down_plate_p8_MediaPrevTrackButton6
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[8].b[6]'
      payload: 'ON'
    action:
      service: media_player.media_previous_track
      <<: *media_player_entity

  # Next Track button action
  - alias: hasp_down_plate_p8_MediaNextTrackButton8
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[8].b[8]'
      payload: 'ON'
    action:
      service: media_player.media_next_track
      <<: *media_player_entity

  - alias: hasp_down_plate_p8_MediaTitle
    trigger:
    - platform: state
      entity_id: sensor.all_speakers_media_title
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    action:
    - service: python_script.hasp_update_message
      data_template:
        nodename: down_plate
        object_id: 'p[8].b[4]'
        text: "{{ states('sensor.all_speakers_media_title')|wordwrap(20, wrapstring='\\r') }}"

  - alias: hasp_down_plate_p8_MediaArtist
    trigger:
    - platform: state
      entity_id: sensor.all_speakers_media_artist
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    action:
    - service: python_script.hasp_update_message
      data_template:
        nodename: down_plate
        object_id: 'p[8].b[5]'
        text: "{{ states('sensor.all_speakers_media_artist')|wordwrap(20, wrapstring='\\r') }}"

  - alias: hasp_down_plate_p8_MediaPlayPause
    trigger:
    - platform: state
      <<: *media_player_entity
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    action:
    - service: python_script.hasp_update_message
      data_template:
        nodename: down_plate
        object_id: 'p[8].b[7]'
        text: >
          {% if is_state('media_player.all_speakers', 'playing') %}
          ;
          {% elif is_state('media_player.all_speakers', 'paused') %}
          4
          {% else %}
          ;
          {% endif %}
        update_font: 'false'

  # Volume slider value published, apply published state
  - alias: hasp_down_plate_p8_MediaVolSliderUpdateHass
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[8].b[9].val'
    action:
    - service: script.harmony_volume
      data_template:
        increment: "{{ (states('input_number.volume_increment'))|int }}"
        entity_id: remote.upstairs_hub
        vol_up: >
          {% if trigger.payload|int > 50 %}
            true
          {% elif trigger.payload|int < 50 %}
            false
          {% endif %}
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[8].b[9].val'
        payload: 50
