###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/20/2018
#  @package      :  Dishwasher
#  @description  :  Handles page 2 on the downstairs HA Wallplate. Page 2 shows
#                   the date/time, downstairs temperature/humidity and the lock
#                   status.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'down_plate_p2'

    automation.hasp_down_plate_p2_Init:
      <<: *customize
    automation.hasp_down_plate_p2_ClockUpdate:
      <<: *customize
    automation.hasp_down_plate_p2_CalendarUpdate:
      <<: *customize
    automation.hasp_down_plate_p2_Weather:
      <<: *customize
    automation.hasp_down_plate_p2_DoorLock:
      <<: *customize

    script.hasp_down_plate_p2_update_clock:
      <<: *customize
    script.hasp_down_plate_p2_update_date:
      <<: *customize
    script.hasp_down_plate_p2_update_weather:
      <<: *customize
    script.hasp_down_plate_p2_update_door_lock:
      <<: *customize

################################################
## Automation
################################################
automation:

  - alias: hasp_down_plate_p2_Init
    trigger:
      - platform: mqtt
        topic: 'hasp/down_plate/status'
        payload: 'ON'
    action:
      - service: script.hasp_down_plate_p2_update_clock
      - service: script.hasp_down_plate_p2_update_date
      - service: script.hasp_down_plate_p2_update_weather
      - service: script.hasp_down_plate_p2_update_door_lock

  # Send the current time every minute
  - alias: hasp_down_plate_p2_ClockUpdate
    trigger:
      - platform: time
        # Matches every minute
        seconds: 00
    condition:
      - condition: state
        entity_id: 'binary_sensor.down_plate_connected'
        state: 'on'
    action:
      - service: script.hasp_down_plate_p2_update_clock

  # Send "Month Day Year" every day, scaling font to fit
  # 0 consolas 24 - 20 chars x 2 lines (wrapped)
  # 1 consolas 32 - 15 chars x 2 lines (wrapped)
  # 2 consolas 48 - 10 chars x 1 line
  # 3 consolas 80 - 6 chars x 1 line
  - alias: hasp_down_plate_p2_CalendarUpdate
    trigger:
      - platform: time
        at: '00:00:00'
    condition:
      - condition: state
        entity_id: 'binary_sensor.down_plate_connected'
        state: 'on'
    action:
      - service: script.hasp_down_plate_p2_update_date

  # Send Temperature/Humidity
  - alias: hasp_down_plate_p2_Weather
    trigger:
      - platform: state
        entity_id: sensor.temperature_158d0002287ef6
      - platform: state
        entity_id: sensor.humidity_158d0002287ef6
    action:
      - service: script.hasp_down_plate_p2_update_weather

  - alias: hasp_down_plate_p2_DoorLock
    trigger:
      - platform: state
        entity_id: lock.front_door
    action:
      - service: script.hasp_down_plate_p2_update_door_lock

################################################
## Script
################################################
script:

  hasp_down_plate_p2_update_clock:
    sequence:
      - service: mqtt.publish
        data:
          topic: 'hasp/down_plate/command/p[2].b[4].txt'
          payload_template: "\"{{(now().strftime('%I')|int)~now().strftime(':%M')}}\""

  hasp_down_plate_p2_update_date:
    sequence:
      - service: mqtt.publish
        data:
          topic: 'hasp/down_plate/command/p[2].b[5].font'
          payload_template: '{% set datelength = (now().strftime("%B %C %Y") ~ now().day)|length %}{% if datelength <= 6 -%}3{% elif (datelength > 6) and (datelength <= 10) %}2{% elif (datelength > 10) and (datelength <= 15) %}1{% else %}0{%- endif %}'
      - service: mqtt.publish
        data:
          topic: 'hasp/down_plate/command/p[2].b[5].txt'
          payload_template: "\"{{now().strftime('%B %C %Y')}}\""

  hasp_down_plate_p2_update_weather:
    sequence:
      - service: mqtt.publish
        data:
          topic: 'hasp/down_plate/command/p[2].b[6].font'
          payload: '1'
      - service: mqtt.publish
        data:
          topic: 'hasp/down_plate/command/p[2].b[6].txt'
          payload_template: "\"{{states('sensor.temperature_158d0002287ef6')}}F|{{states('sensor.humidity_158d0002287ef6')}}%\""

  hasp_down_plate_p2_update_door_lock:
    sequence:
      - service: mqtt.publish
        data:
          topic: 'hasp/down_plate/command/p[2].b[7].font'
          payload: '1'
      - service: mqtt.publish
        data:
          topic: 'hasp/down_plate/command/p[2].b[7].txt'
          payload_template: "\"Doors:{{states('lock.front_door')}}\""
