##############################################################################
# Automations for handling toggle state buttons on page 3
automation:
  # Set font and text for toggle buttons on device connection
  - alias: hasp_down_plate_p3_ToggleInit
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    action:
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[3].b[4]'
        text: 'End Tables'
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[3].b[5]'
        text: 'Couch Accent'
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[3].b[6]'
        text: 'TV Backlight'
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[3].b[7]'
        text: 'Corner Light'

  - alias: hasp_down_plate_p3_ToggleEndTables
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[3].b[4]'
      payload: 'ON'
    action:
      service: homeassistant.toggle
      entity_id: group.end_tables

  - alias: hasp_down_plate_p3_ToggleCouchAccent
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[3].b[5]'
      payload: 'ON'
    action:
      service: homeassistant.toggle
      entity_id: light.couch_accent_white

  - alias: hasp_down_plate_p3_ToggleTVBacklight
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[3].b[6]'
      payload: 'ON'
    action:
      service: homeassistant.toggle
      entity_id: light.extended_color_light_1

  - alias: hasp_down_plate_p3_ToggleCornerLight
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[3].b[7]'
      payload: 'ON'
    action:
      service: homeassistant.toggle
      entity_id: light.living_room_lamp

  - alias: hasp_down_plate_p3_ToggleColor1
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    - platform: state
      entity_id: group.end_tables
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/down_plate/command/p[3].b[4].bco'
        payload_template: >-
          {% if states.group.end_tables.state == "on" -%}
            65535
          {%- else -%}
            25388
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/down_plate/command/p[3].b[4].pco'
        payload_template: >-
          {% if states.group.end_tables.state == "on" -%}
            0
          {%- else -%}
            65535
          {%- endif %}

  - alias: hasp_down_plate_p3_ToggleColor2
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    - platform: state
      entity_id: light.couch_accent_white
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[3].b[5].bco'
        payload_template: >-
          {% if states.light.couch_accent_white.state == "on" -%}
            65535
          {%- else -%}
            25388
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/down_plate/command/p[3].b[5].pco'
        payload_template: >-
          {% if states.light.couch_accent_white.state == "on" -%}
            0
          {%- else -%}
            65535
          {%- endif %}

  - alias: hasp_down_plate_p3_ToggleColor3
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    - platform: state
      entity_id: light.extended_color_light_1
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[3].b[6].bco'
        payload_template: >-
          {% if states.light.extended_color_light_1.state == "on" -%}
            65535
          {%- else -%}
            25388
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/down_plate/command/p[3].b[6].pco'
        payload_template: >-
          {% if states.light.extended_color_light_1.state == "on" -%}
            0
          {%- else -%}
            65535
          {%- endif %}

  - alias: hasp_down_plate_p3_ToggleColor4
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    - platform: state
      entity_id: light.living_room_lamp
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/down_plate/command/p[3].b[6].bco'
        payload_template: >-
          {% if states.light.living_room_lamp.state == "on" -%}
            65535
          {%- else -%}
            25388
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/down_plate/command/p[3].b[6].pco'
        payload_template: >-
          {% if states.light.living_room_lamp.state == "on" -%}
            0
          {%- else -%}
            65535
          {%- endif %}
