##############################################################################
# Automations for handling Scene select buttons on page 1

automation:
  # Set font and text labels for scene buttons on device connection
  - alias: hasp_down_plate_p1_ScenesInit
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/status'
      payload: 'ON'
    action:
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[1].b[4]'
        text: 'All Lights On'
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[1].b[5]'
        text: 'Living Room'
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[1].b[6]'
        text: 'Kitchen'
    - service: python_script.hasp_update_message
      data:
        nodename: down_plate
        object_id: 'p[1].b[7]'
        text: 'All Lights Off'

  # Trigger scene.downstairs_lights_on when p[1].b[4] pressed
  - alias: hasp_down_plate_p1_SceneButton4
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[4]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.downstairs_lights_on

  # Trigger scene.living_room_lights_on when p[1].b[5] pressed
  - alias: hasp_down_plate_p1_SceneButton5
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[5]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.living_room_lights_on

  # Trigger scene.kitchen_lights_on when p[1].b[6] pressed
  - alias: hasp_down_plate_p1_SceneButton6
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[6]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.kitchen_lights_on

  # Trigger scene.downstairs_lights_off when p[1].b[7] pressed
  - alias: hasp_down_plate_p1_SceneButton7
    trigger:
      platform: mqtt
      topic: 'hasp/down_plate/state/p[1].b[7]'
      payload: 'ON'
    action:
      service: scene.turn_on
      entity_id: scene.downstairs_lights_off
