id: server_rack_lights_off
alias: Turn off Server Rack Lights
trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001e07497
    for:
      minutes: 5
    platform: state
    to: 'off'
action:
  - entity_id: switch.server_rack_lights
    service: switch.turn_off
