###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  05/29/2022
#  @package      :  Appliances
#  @description  :  Manages appliances in the house.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'appliances'

################################################
## Automation
################################################

automation:
  - id: 22220e6d-5b70-4718-8a3c-7080f270f928
    alias: Turn on the Hot Water Pump when there is motion in any of the bathrooms
    triggers:
      - trigger: state
        entity_id: binary_sensor.master_bathroom_motion
        from: 'off'
        to: 'on'
      - trigger: state
        entity_id: binary_sensor.hallway_bathroom_motion
        from: 'off'
        to: 'on'
      - trigger: state
        entity_id: binary_sensor.downstairs_bathroom_motion
        from: 'off'
        to: 'on'
      - trigger: state
        entity_id: binary_sensor.kitchen_motion
        from: 'off'
        to: 'on'
    actions:
      - action: switch.turn_on
        entity_id: switch.hot_water_pump
