###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Bathroom
#  @description  :  Controls everything not related to the bathroom fan which
#                   is managed in the bathroom_fan package.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'bathroom'



    ################################################
    ## Automation
    ################################################
    automation.bathroom_light_on:
      <<: *customize

    automation.bathroom_light_off:
      <<: *customize


################################################
## Automation
################################################
automation:

  ################################################
  ## Bathroom Light
  ################################################
  - id: bathroom_light_on
    alias: Turn on the Bathroom Light
    trigger:
      - entity_id: binary_sensor.master_bathroom_motion
        platform: state
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.master_bathroom_lights

  - id: bathroom_light_off
    alias: Turn off the Bathroom Light
    trigger:
      - entity_id: binary_sensor.master_bathroom_motion
        platform: state
        to: 'off'
        for:
          minutes: 5
    action:
      - service: light.turn_off
        entity_id: light.master_bathroom_lights

