###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/05/2018
#  @package      :  Bathroom Fan
#  @description  :  Controls the bathroom fan. Includes humidity, door, and
#                   motion sensors as well as a timer for delayed shutoff. The
#                   timer will not start until all sensors that triggered the
#                   fan activation have stopped triggering.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'bathroom_fan'

      timer_defaults: &timer_defaults
        duration: 300

    input_number.bathroom_fan_triggers:
      <<: *customize

    timer.bathroom_fan_timer:
      <<: *customize

    sensor.bathroom_relative_humidity:
      <<: *customize

    automation.increment_bathroom_fan_triggers:
      <<: *customize
    automation.decrement_bathroom_fan_triggers:
      <<: *customize
    automation.activate_bathroom_fan:
      <<: *customize
    automation.activate_bathroom_fan_timer:
      <<: *customize
    automation.deactivate_bathroom_fan_timer:
      <<: *customize
    automation.deactivate_bathroom_fan:
      <<: *customize
    automation.deactivate_bathroom_fan_on_startup:
      <<: *customize

    script.reset_bathroom_fan_timer:
      <<: *customize

input_number:
  bathroom_fan_triggers:
    name: Bathroom Fan Triggers
    initial: 0
    min: 0
    max: 3
    step: 1

timer:
  bathroom_fan_timer:
    name: Bathroom Fan Timer
    <<: *timer_defaults

sensor:
  - platform: template
    sensors:
      bathroom_relative_humidity:
        friendly_name: 'Relative Humidity'
        unit_of_measurement: '%'
        value_template: '{{ states.sensor.humidity_158d000228846a.state|float - states.sensor.humidity_158d0002249e6f.state|float }}'

################################################
## Automation
################################################

automation:

  ################################################
  ## Bathroom Humidity, Door, Motion Sensors
  ################################################

  - id: increment_bathroom_fan_triggers
    alias: Increment Bathroom Fan Triggers
    trigger:
      # Humidity Detected
      - platform: numeric_state
        entity_id: sensor.bathroom_relative_humidity
        above: 5
      # Door closed
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001de6091
        to: 'off'
      # Motion detected
      - platform: state
        entity_id: group.bathroom_motion
        to: 'on'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bathroom_fan_triggers
          value: >
            {% set entity_id = 'input_number.bathroom_fan_triggers' %}
            {% if states(entity_id) | int < state_attr(entity_id, 'max') %}
              {{ (states(entity_id) | int) + 1 }}
            {% else %}
              {{ states(entity_id) | int }}
            {% endif %}

  - id: decrement_bathroom_fan_triggers
    alias: Decrement Bathroom Fan Triggers
    trigger:
      # Humidity Cleared
      - platform: numeric_state
        entity_id: sensor.bathroom_relative_humidity
        below: 5
        for:
          minutes: 2
      # Door open
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001de6091
        to: 'on'
      # No motion detected
      - platform: state
        entity_id: group.bathroom_motion
        to: 'off'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.bathroom_fan_triggers
          value: >
            {% set entity_id = 'input_number.bathroom_fan_triggers' %}
            {% if states(entity_id) | int > state_attr(entity_id, 'min') %}
              {{ (states(entity_id) | int) - 1 }}
            {% else %}
              {{ states(entity_id) | int }}
            {% endif %}

  ################################################
  ## Bathroom Fan & Timer
  ################################################

  - id: activate_bathroom_fan
    alias: Activate Bathroom Fan
    trigger:
      - platform: state
        entity_id: input_number.bathroom_fan_triggers
    action:
      - service: switch.turn_on
        entity_id: switch.bathroom_fan
      - service: script.reset_bathroom_fan_timer
    condition:
      - condition: numeric_state
        entity_id: input_number.bathroom_fan_triggers
        value_template: '{{ states.input_number.bathroom_fan_triggers.state | int }}'
        above: 0

  - id: activate_bathroom_fan_timer
    alias: Activate Bathroom Fan Timer
    trigger:
      - platform: state
        entity_id: input_number.bathroom_fan_triggers
      - platform: state
        entity_id: switch.bathroom_fan
        to: 'on'
    action:
      - service: timer.start
        entity_id: timer.bathroom_fan_timer
        data:
          <<: *timer_defaults
    condition:
      - condition: numeric_state
        entity_id: input_number.bathroom_fan_triggers
        value_template: '{{ states.input_number.bathroom_fan_triggers.state | int }}'
        below: 1
      - condition: state
        entity_id: switch.bathroom_fan
        state: 'on'

  - id: deactivate_bathroom_fan_timer
    alias: Deactivate Bathroom Fan Timer
    trigger:
      - platform: state
        entity_id: switch.bathroom_fan
        to: 'off'
    action:
      - service: script.reset_bathroom_fan_timer
      - service: input_number.set_value
        data:
          entity_id: input_number.bathroom_fan_triggers
          value: 0

  - id: deactivate_bathroom_fan
    alias: Deactivate Bathroom Fan
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bathroom_fan_timer
    action:
      - service: switch.turn_off
        entity_id: switch.bathroom_fan

  ################################################
  ## Home Assistant Startup/Shutdown
  ################################################

  - id: deactivate_bathroom_fan_on_startup
    alias: Deactivate Bathroom Fan on Startup
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: switch.turn_off
        entity_id: switch.bathroom_fan

################################################
## Script
################################################

script:
  reset_bathroom_fan_timer:
    sequence:
      - service: timer.cancel
        entity_id: timer.bathroom_fan_timer
