###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/13/2018
#  @package      :  Bedroom
#  @description  :  Manages lights and alarms in the bedroom.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'bedroom'

    ################################################
    ## Automation
    ################################################
    automation.bedroom_alarm_triggered:
      <<: *customize

    automation.bedroom_lights_toggle:
      <<: *customize

################################################
## Automation
################################################
automation:

  - id: bedroom_alarm_triggered
    alias: Bedroom Alarm Triggered
    trigger:
      - platform: event
        event_type: ifttt_webhook_received
        event_data:
          cause: alexa_alarm
    action:
      - service: light.turn_on
        entity_id: light.bedroom
        data:
          brightness_pct: 100
          color_temp: 233
      - service: light.turn_on
        entity_id: light.hallway
        data:
          brightness_pct: 100
          color_temp: 233

  - id: bedroom_lights_toggle
    alias: Bedroom Lights Toggle
    trigger:
    - platform: mqtt
      topic: cmnd/sonoff-bedroom-lights/POWER1
    action:
    - entity_id: light.bedroom
      service: light.toggle
