###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/09/2021
#  @package      :  Dining Room
#  @description  :  Logic for handling lights in the Dining Room.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'dining_room'

    light.dining_room_accent_lights:
      <<: *customize

################################################
## Light
################################################
light:
  - platform: switch
    name: Dining Room Accent Lights
    entity_id: switch.dining_room_accent_lights

################################################
## Automation
################################################
automation:
  - id: a4569dfa-806b-4ac6-a302-e843543d9ce6
    alias: Dining Room Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Dining Room.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw30-red-series-switch.yaml
      input:
        zwave_device: 65bf97ecf38c20804024e09dc849c37b
        button_a:
          - service: light.turn_on
            target:
              entity_id: light.dining_room_lights
            data:
              brightness_pct: 100
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.dining_room_accent_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 70
                LED Effect Brightness: 70%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_b:
          - service: light.turn_off
            target:
              entity_id: light.dining_room_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.dining_room_accent_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 70
                LED Effect Brightness: 20%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.dining_room_accent_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.dining_room_accent_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 130
                LED Effect Brightness: 70%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.dining_room_accent_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 130
                LED Effect Brightness: 20%
                LED Effect Duration: 30
                LED Effect Type: Solid
