###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/13/2018
#  @package      :  Dishwasher
#  @description  :  Controls the dishwasher. When the button is single clicked
#                   it enables the dishwasher automatically when the
#                   dishwasher time window begins.
#
#                   @TODO: It sets a persistent
#                   notification when it is complete and then turns off power
#                   to the dishwasher.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'dishwasher'

      sensor_defaults: &sensor_defaults
        <<: *customize
        platform: mqtt
        state_topic: 'tele/sonoff-dishwasher/SENSOR'
        force_update: true

    ################################################
    ## Binary Sensor
    ################################################
    binary_sensor.dishwasher_running:
      <<: *customize

    ################################################
    ## Input Datetime
    ################################################
    input_datetime.dishwasher_start_time:
      <<: *customize

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.dishwasher_enabled:
      <<: *customize

    ################################################
    ## Group
    ################################################
    group.dishwasher_controls:
      <<: *customize

    ################################################
    ## Automation
    ################################################
    automation.enable_dishwasher_when_kitchen_button_pressed:
      <<: *customize

    automation.Disable_dishwasher_when_kitchen_button_double_pressed:
      <<: *customize

    automation.start_dishwasher_at_dishwasher_start_time_if_enabled:
      <<: *customize

    automation.reset_dishwasher_when_complete_if_enabled:
      <<: *customize

################################################
## Sensor
################################################
sensor:
  - name: "Dishwasher Energy"
    <<: *sensor_defaults
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - name: "Dishwasher Power"
    <<: *sensor_defaults
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    unit_of_measurement: "W"
  - name: "Dishwasher Voltage"
    <<: *sensor_defaults
    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
    unit_of_measurement: "V"
  - name: "Dishwasher Current"
    <<: *sensor_defaults
    value_template: '{{ value_json["ENERGY"]["Current"] }}'
    unit_of_measurement: "A"

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      dishwasher_running:
        friendly_name: 'Running'
        value_template: "{{ is_state('switch.dishwasher', 'on') }}"

################################################
## Input Datetime
################################################
input_datetime:
  dishwasher_start_time:
    name: Start Time
    has_date: false
    has_time: true
    initial: '10:00'
    icon: mdi:clock

################################################
## Input Boolean
################################################
input_boolean:
  dishwasher_enabled:
    name: Enabled
    icon: mdi:washing-machine

################################################
## Group
################################################
group:
  dishwasher_controls:
    name: Dishwasher
    control: hidden
    entities:
      - input_boolean.dishwasher_enabled
      - input_datetime.dishwasher_start_time
      - binary_sensor.dishwasher_running

################################################
## Automation
################################################
automation:

  - id: enable_dishwasher_when_kitchen_button_pressed
    alias: Enable Dishwasher when Kitchen Button Pressed
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001e59abe
          click_type: single
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.dishwasher_enabled

  - id: Disable_dishwasher_when_kitchen_button_double_pressed
    alias: Disable Dishwasher when Kitchen Button Double Pressed
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001e59abe
          click_type: double
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.dishwasher_enabled

  - id: start_dishwasher_at_dishwasher_start_time_if_enabled
    alias: Start Dishwasher at Dishwasher Start Time if Enabled
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == ((state_attr('input_datetime.dishwasher_start_time' , 'timestamp'))|timestamp_custom('%H:%M', false)) }}"
    condition:
      - condition: state
        entity_id: input_boolean.dishwasher_enabled
        state: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.dishwasher

  - id: reset_dishwasher_when_complete_if_enabled
    alias: Reset Dishwasher when Complete if Enabled
    trigger:
      - platform: state
        entity_id: switch.dishwasher
        to: 'on'
        for:
          hours: 3
    condition:
      - condition: state
        entity_id: input_boolean.dishwasher_enabled
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.dishwasher
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.dishwasher_enabled
