###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Downstairs Hallway
#  @description  :  Manages equipment in the Downstairs Hallway.
###############################################################################
---

################################################
## Automations
################################################
automation:
  - id: 049cbddb-1796-4df9-be5b-7a6e0335015d
    alias: Control the Downstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Gym Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.downstairs_hallway_tablet_battery_level
        switch_entity: switch.downstairs_hallway_tablet_charger

  - id: '1667032713651'
    alias: Downstairs Hallway Scene Controls
    description: Utilizes a blueprint to control scenes in the Downstairs Hallway.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
      input:
        zwave_device: df9d58e09f02db4bcb1a908a1e32e5e5
        config_button:
          - service: button.press
            data: {}
            target:
              entity_id: button.downstairs_hallway_tablet_restart_browser
        button_a2:
          - service: switch.toggle
            data: {}
            target:
              entity_id: switch.downstairs_hallway_tablet_charger

  - id: 60f9f9b9-ef6e-494d-af89-fd43cdc92d9e
    alias: Control the Downstairs Hallway TV
    description: Turn the Downstairs Hallway TV on/off due to Roku state changes
    trigger:
      - platform: state
        entity_id: media_player.roku_streambar
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.roku_streambar
                state: 'idle'
                for:
                  minutes: 10
            sequence:
              - service: switch.turn_off
                entity_id: switch.downstairs_hallway_tv
          - conditions:
              - condition: state
                entity_id: media_player.roku_streambar
                state: 'on'
            sequence:
              - service: switch.turn_on
                entity_id: switch.downstairs_hallway_tv
