###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Downstairs Hallway
#  @description  :  Manages equipment in the Downstairs Hallway.
###############################################################################
---

################################################
## Automations
################################################
automation:
  - id: 049cbddb-1796-4df9-be5b-7a6e0335015d
    alias: Control the Downstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Gym Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.downstairs_hallway_tablet_battery_level
        switch_entity: switch.downstairs_hallway_tablet_charger
