###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Downstairs Hallway
#  @description  :  Manages equipment in the Downstairs Hallway.
###############################################################################
---

################################################
## Automations
################################################
automation:
  - id: 049cbddb-1796-4df9-be5b-7a6e0335015d
    alias: Control the Downstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Downstairs Hallway Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.downstairs_hallway_tablet_battery
        switch_entity: switch.downstairs_hallway_tablet_charger

  - id: '1667032713651'
    alias: Downstairs Hallway Scene Controls
    description: Utilizes a blueprint to control scenes in the Downstairs Hallway.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch:
          - 1b083dd3571388e94041b98699fb31cf
        config_button:
          - service: button.press
            data: {}
            target:
              entity_id: button.downstairs_hallway_tablet_restart_browser
        button_a2:
          - service: switch.toggle
            data: {}
            target:
              entity_id: switch.downstairs_hallway_tablet_charger
        button_b2:
          - service: switch.toggle
            data: {}
            target:
              entity_id: switch.downstairs_hallway_tv

  - id: 60f9f9b9-ef6e-494d-af89-fd43cdc92d9e
    alias: Control the Downstairs Hallway TV
    description: Turn the Downstairs Hallway TV on/off due to Roku state changes
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id: media_player.roku_streambar
        to: 'on'
      - platform: state
        entity_id: media_player.roku_streambar
        to: 'idle'
        for:
          minutes: 10
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.roku_streambar
                state: 'idle'
            sequence:
              - service: switch.turn_off
                entity_id: switch.downstairs_hallway_tv
          - conditions:
              - condition: state
                entity_id: media_player.roku_streambar
                state: 'on'
            sequence:
              - service: switch.turn_on
                entity_id: switch.downstairs_hallway_tv

  - id: 825c80a1-794c-4f3c-95a9-077ebee85d58
    alias: Update Water Heater Cleaning Status
    description: Show the last cleaning time on the water heater display
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id: input_datetime.water_heater_last_cleaning
    action:
      - service: open_epaper_link.drawcustom
        data:
          background: white
          rotate: 0
          ttl: 300
          dither: true
          payload:
            - type: text
              value: "Last Cleaned"
              font: ppb.ttf
              x: 148
              "y": 32
              size: 30
              color: red
              anchor: mm
            - type: text
              value: "{{ (states('input_datetime.water_heater_last_cleaning') | as_datetime).strftime('%a %m/%d/%Y') }}"
              font: ppb.ttf
              x: 148
              "y": 96
              size: 30
              color: red
              anchor: mm
            - type: line
              x_start: 0
              x_end: 296
              y_start: 64
              y_end: 64
              width: 5
              fill: black
        target:
          entity_id:
            - open_epaper_link.0000021f85043b1c

  - id: 8c282f4e-961c-47d1-9684-cbdef479d216
    alias: Control the Under Stairs Closet Lights
    description: Utilizes the motion_light blueprint for controlling the Under Stairs Closet Lights.
    use_blueprint:
      path: rohankapoorcom/motion_light.yaml
      input:
        motion_entity: binary_sensor.under_stairs_closet_door_window_door_is_open
        light_target: light.under_stairs_closet_lights
        no_motion_wait: 0