###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Downstairs Hallway
#  @description  :  Manages equipment in the Downstairs Hallway.
###############################################################################
---
################################################
## Light
################################################
light:
  - platform: template
    lights:
      stairway_lights:
        friendly_name: Stairway Lights
        unique_id: 25bb040a-ae44-412d-9f6e-4ecbd1cc7816
        value_template: >-
          {{
            is_state('light.stairway_lights_switch', 'on')
            or is_state('light.stairway_scene_controller', 'on')
          }}
        turn_on:
          - service: light.turn_on
            entity_id: light.stairway_lights_switch
        turn_off:
          - service: light.turn_off
            entity_id: light.stairway_lights_switch

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      downstairs_lights_on:
        friendly_name: Downstairs Lights On
        value_template: >
          {{
            is_state('light.stairway_lights', 'on')
            and is_state('light.downstairs_hallway_lights', 'on')
          }}
      downstairs_lights_off:
        friendly_name: Downstairs Lights Off
        value_template: >
          {{
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('downstairs_bathroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            + 
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('downstairs_hallway'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('garage'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('guest_room'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('gym'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            == 0
          }}
      upstairs_lights_on:
        friendly_name: Upstairs Lights On
        value_template: >
          {{
            is_state('light.hallway_lights', 'on')
            and is_state('light.kitchen_cabinet_lights', 'on')
          }}
      upstairs_lights_off:
        friendly_name: Upstairs Lights Off
        value_template: >
          {{
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('hallway'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            + 
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('hallway_bathroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('living_room'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('kitchen'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('dining_room'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('master_bathroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('master_bedroom'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            +
            expand(states.light)
            | selectattr('entity_id', 'in', area_entities('office'))
            | selectattr('state', 'eq', 'on')
            | map(attribute='entity_id')
            | list
            | count
            == 0
          }}

################################################
## Automations
################################################
automation:
  - id: 049cbddb-1796-4df9-be5b-7a6e0335015d
    alias: Control the Downstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Gym Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.downstairs_hallway_tablet_battery_level
        switch_entity: switch.downstairs_hallway_tablet_charger

  - id: '1644120951513'
    alias: Stairway Scene Controller
    description: 'Utilizes a blueprint to control scenes on the stairway.'
    use_blueprint:
      path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
      input:
        zooz_switch: 7829e6b1bbb429e88c159df549586393
        scene_1:
          - service: light.turn_on
            target:
              entity_id:
                - light.hallway_lights
                - light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
        scene_2:
          - service: light.turn_on
            target:
              area_id:
                - downstairs_hallway
        scene_3:
          - service: light.turn_off
            target:
              area_id:
                - hallway
                - hallway_bathroom
                - living_room
                - kitchen
                - dining_room
                - master_bathroom
                - master_bedroom
                - office
        scene_4:
          - service: light.turn_off
            target:
              area_id:
                - downstairs_bathroom
                - downstairs_hallway
                - garage
                - guest_room
                - gym

  - id: '1667032713651'
    alias: Downstairs Hallway Scene Controls
    description: Utilizes a blueprint to control scenes in the Downstairs Hallway.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
      input:
        zwave_device: df9d58e09f02db4bcb1a908a1e32e5e5
        config_button:
          - service: button.press
            data: {}
            target:
              entity_id: button.downstairs_hallway_tablet_restart_browser
        button_a2:
          - service: switch.toggle
            data: {}
            target:
              entity_id: switch.downstairs_hallway_tablet_charger

  - id: 'f248725a-26e6-46f7-becd-bc53ccc662ef'
    alias: Stairway Scene Controller Status Lights
    description: 'Utilizes a blueprint to map track lighting states on the Scene Controller on the Stairway.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controller-status-lights.yaml
      input:
        zooz_switch: 7829e6b1bbb429e88c159df549586393
        small_1_button_light: binary_sensor.upstairs_lights_on
        small_2_button_light: binary_sensor.downstairs_lights_on
        small_3_button_light: binary_sensor.upstairs_lights_off
        small_4_button_light: binary_sensor.downstairs_lights_off
