###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Downstairs Hallway
#  @description  :  Manages equipment in the Downstairs Hallway.
###############################################################################
---

################################################
## Automations
################################################
automation:
  - id: 049cbddb-1796-4df9-be5b-7a6e0335015d
    alias: Control the Downstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Gym Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.downstairs_hallway_tablet_battery_level
        switch_entity: switch.downstairs_hallway_tablet_charger

  - id: '1644120951513'
    alias: Stairway Scene Controller
    description: 'Utilizes a blueprint to control scenes on the stairway.'
    use_blueprint:
      path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
      input:
        zooz_switch: 7829e6b1bbb429e88c159df549586393
        scene_3:
        - service: light.turn_off
          target:
            area_id:
            - hallway
            - hallway_bathroom
            - e857fce8973b475c9d1b4479c2494139
            - c74119fdbc01442e8932a5a871e3b700
            - c04b2ee0de40464288a1a50ab1b110ce
            - bc081ff944ea41e383a982bca696d6cb
            - faa7cc1b598b4635bd2b0349b6d0682d
            - c8e64155949842d5be77f5c329e2496c
        scene_4:
        - service: light.turn_off
          target:
            area_id:
            - downstairs_bathroom
            - f70fb5d3de3649469d6146a3f1422009
            - 8b6baf03d42142eca2ecfedee50ab9fa
            - 26f1ffed8937795679d686c14f7974ad
            - storage_room