###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/24/22
#  @package      :  Front Door
#  @description  :  Controls things near the front door
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'front_door'

automation:
  - id: 304cad1d-c405-4479-9177-2beb93c46cae
    alias: Control the Front Door Lights
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.front_door_motion_sensor
        from: 'off'
        to: 'on'
    actions:
      - choose:
          - alias: If it's dark and there is motion, then turn on the lights.
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.front_door_motion_sensor
                    state: 'on'
                  - condition: numeric_state
                    entity_id: sensor.garage_entry_motion_sensor_illuminance
                    below: 100

            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.front_door_lights
              - wait_for_trigger:
                  - trigger: template
                    value_template: >
                      {{ is_state('binary_sensor.front_door_motion_sensor', 'off') }}
                continue_on_timeout: false
              - delay:
                  minutes: 1
              - action: light.turn_off
                target:
                  entity_id: light.front_door_lights
        default:
          - action: light.turn_off
            entity_id: light.front_door_lights
