###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Gym
#  @description  :  Manages equipment in the Gym.
###############################################################################
---

################################################
## Automations
################################################
automation:
  - id: dd25ecc8-aaee-4a32-8b38-90b13db78b09
    alias: Control the Gym Tablet Charger
    description: Utilizes a blueprint to manage charging the Gym Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.gym_tablet_battery
        switch_entity: switch.gym_tablet_charger

  - id: '1667032908768'
    alias: Gym Scene Controls
    description: Utilizes a blueprint to control scenes with the Gym Lightswitch.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-switch.yaml
      input:
        zwave_device: 4ef91ee5285ec4ad43cb3dbf25b3faf7
        config_button:
          - service: cover.toggle
            target:
              entity_id: cover.gym_shades
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id: 4ef91ee5285ec4ad43cb3dbf25b3faf7
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 20
                All LED Strip Effect - Effect: Open/close
        config_button2:
          - service: button.press
            data: {}
            target:
              entity_id:
                - button.gym_tablet_restart_browser
        button_a2:
          - service: fan.turn_on
            data: {}
            target:
              entity_id: fan.gym_fan
        button_b2:
          - service: fan.turn_off
            data: {}
            target:
              entity_id: fan.gym_fan

  - id: 067c456d-a3fa-4ee2-9969-b2a48445e369
    alias: Manage the Gym Shades
    description: Automatically open/close the Gym Shades based on the Sun Position
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
        offset: '+1:30:00'
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
    action:
      - choose:
          - alias: If it's after sunset or before sunrise, then close the shade.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: sun
                    before: sunrise
                    before_offset: '+1:30:00'
            sequence:
              - service: cover.close_cover
                target:
                  entity_id: cover.gym_shades
          - alias: If it's 90 minutes after sunrise, then open the shade.
            conditions:
              - condition: sun
                after: sunrise
                after_offset: '+1:30:00'
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.gym_shades
      - service: zwave_js.bulk_set_partial_config_parameters
        target:
          device_id: 4ef91ee5285ec4ad43cb3dbf25b3faf7
        data:
          parameter: 99
          value:
            All LED Strip Effect - Color: 170
            All LED Strip Effect - Level: 50
            All LED Strip Effect - Duration: 20
            All LED Strip Effect - Effect: Open/close
    mode: single
