###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/19/2022
#  @package      :  Gym
#  @description  :  Manages equipment in the Gym.
###############################################################################
---

################################################
## Automations
################################################
automation:
  - id: dd25ecc8-aaee-4a32-8b38-90b13db78b09
    alias: Control the Gym Tablet Charger
    description: Utilizes a blueprint to manage charging the Gym Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.gym_tablet_battery_level
        switch_entity: switch.gym_tablet_charger

  - id: '1667032908768'
    alias: Gym Scene Controls
    description: Utilizes a blueprint to control scenes with the Gym Lightswitch.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
      input:
        zwave_device: 4ef91ee5285ec4ad43cb3dbf25b3faf7
        config_button:
          - service: button.press
            data: {}
            target:
              entity_id:
                - button.gym_tablet_restart_browser
        button_a2:
          - service: fan.turn_on
            data: {}
            target:
              entity_id: fan.gym_fan
        button_b2:
          - service: fan.turn_off
            data: {}
            target:
              entity_id: fan.gym_fan
