###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/11/2018
#  @package      :  HA System
#  @description  :  Manages aspects of the home assistant system
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'ha_system'

    sensor.rohankapoorcomhomeassistantconfig_last_build_state:
      <<: *customize

    sensor.current_git_commit_id:
      <<: *customize

    sensor.current_git_commit_time:
      <<: *customize

    automation.update_configuration_if_travis_build_is_successful:
      <<: *customize

    shell_command.git_pull:
      <<: *customize

    script.pull_and_restart_homeassistant:
      <<: *customize

################################################
## Sensor
################################################

sensor:

  - platform: travisci
    api_key: !secret sensor.travis.api_key
    repository:
      - homeassistant-config
    branch:
      - master
    monitored_conditions:
      - last_build_state

  - platform: command_line
    name: current_git_commit_id
    command: '/usr/bin/git -C /etc/homeassistant/ rev-parse HEAD'

  - platform: command_line
    name: current_git_commit_time
    command: '/usr/bin/git -C /etc/homeassistant/ log -1 --format="%at" | /usr/bin/xargs -I{} date -ud @{} +"%Y-%m-%dT%H:%M:%S.000Z"'

################################################
## Automation
################################################

automation:

  - id: update_configuration_if_travis_build_is_successful
    alias: Update configuration if travis build is successful
    trigger:
      - entity_id: sensor.rohankapoorcomhomeassistantconfig_last_build_state
        platform: state
        to: 'passed'
    condition:
      - condition: template
        value_template: "{{ is_state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Commit Branch', 'master') }}"
      - condition: template
        value_template: "{{ not is_state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Commit SHA', states('sensor.current_git_commit_id')) }}"
      - condition: template
        value_template: "{{ states('sensor.current_git_commit_time') < state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Committed Date') }}"
    action:
      - service: script.pull_and_restart_homeassistant

################################################
## Shell Command
################################################

shell_command:
  git_pull: "/usr/bin/git -C /etc/homeassistant/ pull"

################################################
## Script
################################################

script:
  pull_and_restart_homeassistant:
    sequence:
      - service: shell_command.git_pull
      - wait_template: "is_state_attr('sensor.rohankapoorcomhomeassistantconfig_last_build_state', 'Commit SHA', sensor.current_git_commit_id) }}"
      - service: homeassistant.restart
