###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

    ################################################
    ## Light
    ################################################
    light.hallway_lights:
      <<: *customize
      supported_features: 33

    light.stairway_lights:
      <<: *customize

################################################
## Light
################################################
light:
  - platform: group
    name: Hallway Lights
    unique_id: 00592bd8-5689-4280-945a-de12766bd25d
    entities:
      - light.hallway_lights_switch
      - light.entryway_lights

  - platform: switch
    name: Stairway Lights
    unique_id: 1f74d706-206c-49fb-ba67-57909b253531
    entity_id: switch.stairway_lights
