###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

    ################################################
    ## Light
    ################################################
    light.hallway_lights:
      <<: *customize
      supported_features: 33

    light.stairway_lights:
      <<: *customize

################################################
## Light
################################################
light:
  - platform: group
    name: Hallway Lights
    unique_id: 00592bd8-5689-4280-945a-de12766bd25d
    entities:
      - light.hallway_lights_switch
      - light.entryway_lights

  - platform: switch
    name: Stairway Lights
    entity_id: switch.stairway_lights

################################################
## Automations
################################################
automation:
  - id: 0de6a925-9ceb-42fb-b7be-f6621be3ed09
    alias: Control the Hallway Tablet Charger
    description: Turn on the Hallway Tablet Charger when the battery is below 40% and turn it off when it's above 85%.
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: numeric_state
        entity_id: sensor.upstairs_hallway_tablet_battery_level
        above: 85
      - platform: numeric_state
        entity_id: sensor.upstairs_hallway_tablet_battery_level
        below: 40

    action:
      - choose:
          - alias: If the battery is above 85%, then turn off the charger.
            conditions:
              - condition: numeric_state
                entity_id: sensor.upstairs_hallway_tablet_battery_level
                above: 85
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.hallway_tablet_charger
          - alias: If the battery is below 40%, then turn on the charger.
            conditions:
              - condition: numeric_state
                entity_id: sensor.upstairs_hallway_tablet_battery_level
                below: 40
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.hallway_tablet_charger
        default:
          - service: switch.turn_off
            target:
              entity_id: switch.hallway_tablet_charger

  - id: '1641371956033'
    alias: Hallway Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Hallway.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
      input:
        zwave_device: 88136be71050b07599ec3caf5928e7a5
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.hallway_lights_switch
            data:
              parameter: 16
              value:
                LED Effect Color: 70
                LED Effect Brightness: 70%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.hallway_lights_switch
            data:
              parameter: 16
              value:
                LED Effect Color: 70
                LED Effect Brightness: 20%
                LED Effect Duration: 30
                LED Effect Type: Solid
