###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

    ################################################
    ## Light
    ################################################

    light.stairway_lights:
      <<: *customize

################################################
## Light
################################################
light:
  - platform: template
    lights:
      stairway_lights:
        friendly_name: Stairway Lights
        unique_id: 25bb040a-ae44-412d-9f6e-4ecbd1cc7816
        value_template: >-
          {{
            is_state('light.stairway_lights_switch', 'on')
            or is_state('light.stairway_scene_controller', 'on')
          }}
        turn_on:
          - service: light.turn_on
            entity_id: light.stairway_lights_switch
        turn_off:
          - service: light.turn_off
            entity_id: light.stairway_lights_switch

################################################
## Automations
################################################
automation:
  - id: 0de6a925-9ceb-42fb-b7be-f6621be3ed09
    alias: Control the Upstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Hallway Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.upstairs_hallway_tablet_battery_level
        switch_entity: switch.upstairs_hallway_tablet_charger
