###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/23/2021
#  @package      :  Hallway Bathroom
#  @description  :  Controls lights and fans in the Hallway Bathroom.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway_bathroom'

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      hallway_bathroom_relative_humidity:
        friendly_name: 'Relative Humidity'
        unit_of_measurement: '%'
        value_template: >
          {{ states('sensor.hallway_bathroom_humidity') | float(0) - states('sensor.upstairs_humidity') | float(0) }}

################################################
## Automation
################################################
automation:
  - id: a04b7289-134e-4920-8174-c04e00d1be77
    alias: Control the Hallway Bathroom Lights
    description: Utilizes the motion_light blueprint for contolling the Hallway Bathroom Lights.
    use_blueprint:
      path: rohankapoorcom/motion_light.yaml
      input:
        motion_entity: binary_sensor.hallway_bathroom_motion
        light_target: light.hallway_bathroom_lights
        no_motion_wait: 300

  - id: 5c050332-9c23-4125-82f8-2cec45fb0e7a
    alias: Control the Hallway Bathroom Fan
    description: Utilizes motion and humidity for controlling the Hallway Bathroom Fan.
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id: binary_sensor.hallway_bathroom_motion
        from: 'off'
        to: 'on'
      - platform: numeric_state
        entity_id: sensor.hallway_bathroom_relative_humidity
        above: 20
    action:
      - choose:
          - alias: If there is motion or high humidity, then turn on the fan.
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.hallway_bathroom_motion
                    state: 'on'
                  - condition: numeric_state
                    entity_id: sensor.hallway_bathroom_relative_humidity
                    above: 20
            sequence:
              - service: fan.turn_on
                target:
                  entity_id: fan.hallway_bathroom_fan
              - wait_for_trigger:
                  - platform: template
                    value_template: >
                      {{ states('sensor.hallway_bathroom_relative_humidity') | float <= 10
                      and is_state('binary_sensor.hallway_bathroom_motion', 'off') }}
                continue_on_timeout: false
              - delay:
                  minutes: 5
              - service: fan.turn_off
                target:
                  entity_id: fan.hallway_bathroom_fan
        default:
          - service: fan.turn_off
            target:
              entity_id: fan.hallway_bathroom_fan

  - id: 0b252966-863d-4f1c-93b8-c4d4154b0aff
    alias: Adjust the Hallway Bathroom Default Brightness
    description: Utilizes a blueprint to configure the default brightess on the Hallway Bathroom Lights.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw31-sn-red-series-night-mode.yaml
      input:
        zwave_device: b6df24a18353633370965899bb1e9a05
        bedtime: '01:00:00'
        bedtime_brightness: 10
        wakeup_time: '08:00:00'
        wakeup_time_brightness: 99

  - id: 1e07a741-80f4-4c08-b8cd-7cb33849812d
    alias: Hallway Bathroom Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Hallway Bathroom.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
      input:
        zwave_device: b6df24a18353633370965899bb1e9a05
        button_a:
          - service: light.turn_on
            target:
              entity_id: light.hallway_bathroom_lights
            data:
              brightness_pct: 100
