###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

    ################################################
    ## Light
    ################################################
    light.hallway_lights:
      <<: *customize
      id: 84b4f4a0-97d9-4e4d-89e8-185402b86669
      supported_features: 33

    light.stairway_lights:
      <<: *customize


################################################
## Light
################################################
light:
  - platform: group
    name: Hallway Lights
    entities:
      - light.hallway_lights_switch
      - light.entryway_lights

  - platform: switch
    name: Stairway Lights
    entity_id: switch.stairway_lights
