###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

    ################################################
    ## Light
    ################################################
    light.hallway_lights:
      <<: *customize
      supported_features: 33

    light.stairway_lights:
      <<: *customize

################################################
## Light
################################################
light:
  - platform: group
    name: Hallway Lights
    unique_id: 00592bd8-5689-4280-945a-de12766bd25d
    entities:
      - light.hallway_lights_switch
      - light.entryway_lights

  - platform: switch
    name: Stairway Lights
    entity_id: switch.stairway_lights

################################################
## Automations
################################################
automation:
  - id: 0de6a925-9ceb-42fb-b7be-f6621be3ed09
    alias: Control the Hallway Tablet Charger
    description: Turn on the Hallway Tablet Charger when the battery is below 40% and turn it off when it's above 85%.
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: numeric_state
        entity_id: sensor.upstairs_hallway_tablet_battery_level
        above: 85
      - platform: numeric_state
        entity_id: sensor.upstairs_hallway_tablet_battery_level
        below: 40

    action:
      - choose:
          - alias: If the battery is above 85%, then turn off the charger.
            conditions:
              - condition: numeric_state
                entity_id: sensor.upstairs_hallway_tablet_battery_level
                above: 85
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.hallway_tablet_charger
          - alias: If the battery is below 40%, then turn on the charger.
            conditions:
              - condition: numeric_state
                entity_id: sensor.upstairs_hallway_tablet_battery_level
                below: 40
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.hallway_tablet_charger
        default:
          - service: switch.turn_off
            target:
              entity_id: switch.hallway_tablet_charger