###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Hallway
#  @description  :  Manages lighting in the hallway
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'hallway'

################################################
## Automations
################################################
automation:
  - id: 0de6a925-9ceb-42fb-b7be-f6621be3ed09
    alias: Control the Upstairs Hallway Tablet Charger
    description: Utilizes a blueprint to manage charging the Hallway Tablet.
    use_blueprint:
      path: rohankapoorcom/tablet-battery-charging.yaml
      input:
        battery_entity: sensor.upstairs_hallway_tablet_battery
        switch_entity: switch.upstairs_hallway_tablet_charger

  - id: '1643337826040'
    alias: Upstairs Hallway Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Upstairs Hallway.
    use_blueprint:
      path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
      input:
        zooz_switch: 4418d1607160e581af11597ef65ef295
        scene_1:
          - service: light.toggle
            target:
              entity_id: light.dining_room_lights
        scene_2:
          - service: light.toggle
            target:
              entity_id: light.dining_room_accent_lights
        scene_4:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: light.kitchen_cabinet_lights
                    state: 'on'
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: light.kitchen_cabinet_lights
                    data:
                      transition: 2
            default:
              - service: light.turn_on
                target:
                  entity_id: light.kitchen_cabinet_lights
                data:
                  brightness_pct: 100
                  kelvin: 3000
                  transition: 2
        scene_3:
          - service: light.toggle
            target:
              entity_id: light.kitchen_lights

  - id: '1643339651442'
    alias: Upstairs Hallway Scene Controller Status Lights
    description: 'Utilizes a blueprint to map track lighting states on the Scene Controller in the Upstairs Hallway.'
    use_blueprint:
      path: rohankapoorcom/zooz-zen32-scene-controller-status-lights.yaml
      input:
        zooz_switch: 4418d1607160e581af11597ef65ef295
        large_button_light: light.hallway_lights
        small_1_button_light: light.dining_room_lights
        small_2_button_light: light.dining_room_accent_lights
        small_3_button_light: light.kitchen_lights
        small_4_button_light: light.kitchen_cabinet_lights
