###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen'

    light.kitchen_lights:
      <<: *customize

################################################
## Light
################################################
light:
  - platform: switch
    name: Kitchen Lights
    entity_id: switch.kitchen_lights

################################################
## Automation
################################################
automation:
  - id: 47c666bc-1a15-44ee-9712-d9ae472ad785
    alias: Kitchen Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw30-red-series-switch.yaml
      input:
        zwave_device: 5d8cc12a755640bb788ec4a171f8ac4e
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                0xff: 70
                0xff00: 70%
                0xff0000: 30
                0x7f000000: Solid
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                0xff: 70
                0xff00: 20%
                0xff0000: 30
                0x7f000000: Solid
        button_a3:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                0xff: 130
                0xff00: 70%
                0xff0000: 30
                0x7f000000: Solid
        button_b3:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                0xff: 130
                0xff00: 20%
                0xff0000: 30
                0x7f000000: Solid
        button_a4:
          - service: light.turn_on
            target:
              area_id: c74119fdbc01442e8932a5a871e3b700
            data:
              brightness_pct: 100
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                0xff: 142
                0xff00: 70%
                0xff0000: 30
                0x7f000000: Solid
        button_b4:
          - service: light.turn_off
            target:
              area_id: c74119fdbc01442e8932a5a871e3b700
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                0xff: 142
                0xff00: 20%
                0xff0000: 30
                0x7f000000: Solid