###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen'

    kitchen_light_switch_device_ids: &kitchen_light_switch_device_ids
      - f9923a84b8a3dab105d7695f9d08b6f4

################################################
## Light
################################################
light:

  - platform: group
    name: Kitchen Cabinet Lights
    unique_id: b5d9b202-096a-4fa1-80eb-6d2c4f491374
    entities:
      - light.kitchen_cabinet_lower_lights
      - light.kitchen_cabinet_upper_lights

################################################
## Automation
################################################
automation:
  - id: 3c66912f-0aa1-469f-9b91-93bfa7c2711f
    alias: Kitchen Light Switch Zigbee Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch: 5580d638554510eabf0b5d3dbabe1263
        config_button:
          - service: cover.toggle
            target:
              entity_id: cover.kitchen_shades
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 170
              level: 50
              effect: Open/Close
              duration: 20 Seconds
              target:
                device_id: 5580d638554510eabf0b5d3dbabe1263
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id: 5580d638554510eabf0b5d3dbabe1263
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id: 5580d638554510eabf0b5d3dbabe1263
        button_a3:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id: 5580d638554510eabf0b5d3dbabe1263
        button_b3:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id: 5580d638554510eabf0b5d3dbabe1263
        button_a4:
          - service: light.turn_on
            target:
              area_id: kitchen
            data:
              brightness_pct: 100
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id: 5580d638554510eabf0b5d3dbabe1263
        button_b4:
          - service: light.turn_off
            target:
              area_id: kitchen
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id: 5580d638554510eabf0b5d3dbabe1263

  - id: 47c666bc-1a15-44ee-9712-d9ae472ad785
    alias: Kitchen Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-switch.yaml
      input:
        zwave_device:
          *kitchen_light_switch_device_ids
        config_button:
          - service: cover.toggle
            target:
              entity_id: cover.kitchen_shades
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 20
                All LED Strip Effect - Effect: Open/close
        button_a1:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
            data:
              brightnesss_pct: 100
        button_b1:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 70
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium rise
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 70
                All LED Strip Effect - Level: 10
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium fall
        button_a3:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 130
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium rise
        button_b3:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 130
                All LED Strip Effect - Level: 10
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium fall
        button_a4:
          - service: light.turn_on
            target:
              area_id: kitchen
            data:
              brightness_pct: 100
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 142
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium rise
        button_b4:
          - service: light.turn_off
            target:
              area_id: kitchen
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 142
                All LED Strip Effect - Level: 10
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium fall

  - id: ea920c86-437a-4224-8329-7cad4537dc1a
    alias: Manage the Kitchen Shades
    description: Automatically open/close the Kitchen Shades based on the Sun Position
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
        offset: '+1:30:00'
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
    action:
      - choose:
          - alias: If it's after sunset or before sunrise, then close the shade.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: sun
                    before: sunrise
                    before_offset: '+1:30:00'
            sequence:
              - service: cover.close_cover
                target:
                  entity_id: cover.kitchen_shades
          - alias: If it's 90 minutes after sunrise, then open the shade.
            conditions:
              - condition: sun
                after: sunrise
                after_offset: '+1:30:00'
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.kitchen_shades
      - service: zwave_js.bulk_set_partial_config_parameters
        target:
          device_id:
            *kitchen_light_switch_device_ids
        data:
          parameter: 99
          value:
            All LED Strip Effect - Color: 170
            All LED Strip Effect - Level: 50
            All LED Strip Effect - Duration: 20
            All LED Strip Effect - Effect: Open/close
      - service: script.inovelli_blue_notifications
        data:
          led: All
          color: 170
          level: 50
          effect: Open/Close
          duration: 20 Seconds
          target:
            device_id: 5580d638554510eabf0b5d3dbabe1263
    mode: single
