###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen'

    kitchen_light_switch_device_ids: &kitchen_light_switch_device_ids
      - 5580d638554510eabf0b5d3dbabe1263
      - 1ba8afa3f33d85ff33d77a5a13dfd364

################################################
## Light
################################################
light:

  - platform: group
    name: Kitchen Cabinet Lights
    unique_id: b5d9b202-096a-4fa1-80eb-6d2c4f491374
    entities:
      - light.kitchen_cabinet_lower_lights
      - light.kitchen_cabinet_upper_lights

################################################
## Script
################################################
script:
  update_dishwasher_display:
    description: "Update the dishwasher display with the current state"
    fields:
      state:
        description: "The current state of the dishwasher (Clean, Dirty, Running)"
        example: Running
    sequence:
      - service: open_epaper_link.drawcustom
        data:
          background: white
          rotate: 0
          ttl: 300
          dither: false
          payload:
            - type: text
              value: "{{ state }}"
              font: ppb.ttf
              x: 220
              y: 64
              size: 70
              color: red
              anchor: mm
            - type: text
              value: As of {{ now().strftime('%m/%d/%Y at %I:%M %p') }}
              font: ppb.ttf
              x: 375
              y: 160
              size: 15
              color: black
              anchor: rs
            - type: icon
              value: silverware-clean
              x: 40
              y: 64
              size: 60
              color: black
              anchor: mm
            - type: text
              value: Dirty
              font: ppb.ttf
              x: 15
              y: 130
              size: 15
              color: black
              anchor: ls
            - type: text
              value: Clean
              font: ppb.ttf
              x: 100
              y: 130
              size: 15
              color: black
              anchor: ls
            - type: icon
              value: arrow-down
              x: 33
              y: 160
              size: 25
              color: red
              anchor: ms
            - type: icon
              value: arrow-down
              x: 125
              y: 160
              size: 25
              color: red
              anchor: ms
        target:
          entity_id:
            - open_epaper_link.00007E1F8BCCB294

################################################
## Automation
################################################
automation:
  - id: 6eb0e509-5d18-401a-87e1-d05a7b3854f6
    alias: Update Dishwasher Display
    description: "Set Dishwasher Display status based on power usage"
    use_blueprint:
      path: >-
        sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
      input:
        power_sensor: sensor.energy_monitor_2_dishwasher_power
        starting_threshold: 25
        finishing_threshold: 15
        actions:
          - service: script.update_dishwasher_display
            data:
              state: Clean
        starting_hysteresis: 5
        finishing_hysteresis: 10
        pre_actions:
          - service: script.update_dishwasher_display
            data:
              state: Running

  - id: 035831df-c284-4935-93fd-a337e2890b8c
    alias: Dishwasher Display Button Triggers
    description: Change the dishwasher display based on buttons triggered
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: open_epaper_link_event
        event_data:
          device_id: 00007E1F8BCCB294
    action:
      - variables:
          button_id: '{{ trigger.event.data.type }}'
      - choose:
          - alias: If the clean_button was clicked, set the display to Clean
            conditions: '{{ button_id == "BUTTON1" }}'
            sequence:
              - service: script.update_dishwasher_display
                data:
                  state: Clean
          - alias: If the dirty_button was clicked, set the display to Dirty
            conditions: '{{ button_id == "BUTTON2" }}'
            sequence:
              - service: script.update_dishwasher_display
                data:
                  state: Dirty

  - id: 3c66912f-0aa1-469f-9b91-93bfa7c2711f
    alias: Kitchen Light Switch Zigbee Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch: *kitchen_light_switch_device_ids
        config_button:
          - service: cover.toggle
            target:
              entity_id: cover.kitchen_shades
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 170
              level: 50
              effect: Open/Close
              duration: 20 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a3:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b3:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a4:
          - service: light.turn_on
            target:
              area_id: kitchen
            data:
              brightness_pct: 100
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b4:
          - service: light.turn_off
            target:
              area_id: kitchen
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids

  - id: ea920c86-437a-4224-8329-7cad4537dc1a
    alias: Manage the Kitchen Shades
    description: Automatically open/close the Kitchen Shades based on the Sun Position
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
        offset: '+1:30:00'
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
    action:
      - choose:
          - alias: If it's after sunset or before sunrise, then close the shade.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: sun
                    before: sunrise
                    before_offset: '+1:30:00'
            sequence:
              - service: cover.close_cover
                target:
                  entity_id: cover.kitchen_shades
          - alias: If it's 90 minutes after sunrise, then open the shade.
            conditions:
              - condition: sun
                after: sunrise
                after_offset: '+1:30:00'
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.kitchen_shades
      - service: script.inovelli_blue_notifications
        data:
          led: All
          color: 170
          level: 50
          effect: Open/Close
          duration: 20 Seconds
          target:
            device_id:
              *kitchen_light_switch_device_ids
    mode: single
