###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen'

    light.kitchen_lights:
      <<: *customize

################################################
## Light
################################################
light:
  - platform: switch
    name: Kitchen Lights
    entity_id: switch.kitchen_lights

  - platform: group
    name: Kitchen Cabinet Lights
    unique_id: b5d9b202-096a-4fa1-80eb-6d2c4f491374
    entities:
      - light.kitchen_cabinet_lower_lights
      - light.kitchen_cabinet_upper_lights

################################################
## Automation
################################################
automation:
  - id: 47c666bc-1a15-44ee-9712-d9ae472ad785
    alias: Kitchen Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw30-red-series-switch.yaml
      input:
        zwave_device: cd14590ea99636c9f80266b42ab036b8
        config_button:
          - service: cover.toggle
            target:
              entity_id: cover.kitchen_shades
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 70
                LED Effect Brightness: 70%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 70
                LED Effect Brightness: 20%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_a3:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 130
                LED Effect Brightness: 70%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_b3:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 130
                LED Effect Brightness: 20%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_a4:
          - service: light.turn_on
            target:
              area_id: kitchen
            data:
              brightness_pct: 100
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 142
                LED Effect Brightness: 70%
                LED Effect Duration: 30
                LED Effect Type: Solid
        button_b4:
          - service: light.turn_off
            target:
              area_id: kitchen
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              entity_id: switch.kitchen_lights
            data:
              parameter: 8
              value:
                LED Effect Color: 142
                LED Effect Brightness: 20%
                LED Effect Duration: 30
                LED Effect Type: Solid

  - id: ea920c86-437a-4224-8329-7cad4537dc1a
    alias: Manage the Kitchen Shades
    description: Automatically open/close the Kitchen Shades based on the Sun Position
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
        offset: '+1:30:00'
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
    action:
      - choose:
          - alias: If it's after sunset or before sunrise, then close the shade.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: sun
                    before: sunrise
                    before_offset: '+1:30:00'
            sequence:
              - service: cover.close_cover
                target:
                  entity_id: cover.kitchen_shades
          - alias: If it's 90 minutes after sunrise, then open the shade.
            conditions:
              - condition: sun
                after: sunrise
                after_offset: '+1:30:00'
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.kitchen_shades
    mode: single
