###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen'

    kitchen_light_switch_device_ids: &kitchen_light_switch_device_ids
      - 5580d638554510eabf0b5d3dbabe1263
      - 1ba8afa3f33d85ff33d77a5a13dfd364

################################################
## Light
################################################
light:

  - platform: group
    name: Kitchen Cabinet Lights
    unique_id: b5d9b202-096a-4fa1-80eb-6d2c4f491374
    entities:
      - light.kitchen_cabinet_lower_lights
      - light.kitchen_cabinet_upper_lights

################################################
## Automation
################################################
automation:
  - id: 6eb0e509-5d18-401a-87e1-d05a7b3854f6
    alias: Mark Dishwasher as Clean
    description: "Set Dishwasher to Clean when power usage drops off after running"
    use_blueprint:
      path: >-
        sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
      input:
        power_sensor: sensor.energy_monitor_2_dishwasher_power
        starting_threshold: 25
        finishing_threshold: 15
        actions:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.dishwasher_is_clean
        starting_hysteresis: 5
        finishing_hysteresis: 5
        pre_actions:

  - id: 035831df-c284-4935-93fd-a337e2890b8c
    alias: Hallway Light Switch (Kitchen) Zigbee Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen (Hallway Light Switch).
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch:
          - a7a4f8a1f6c1b0d3cf9496e0aa1ae1c4
        config_button:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.dishwasher_is_clean

  - id: 61db2c80-f34e-4d73-b9e1-b6ed273a325c
    alias: Update Dishwasher Display
    description: Show the Clean / Dirty state of the dishwasher
    trigger:
      - platform: state
        entity_id: input_boolean.dishwasher_is_clean
    action:
      - service: open_epaper_link.drawcustom
        data:
          background: white
          rotate: 0
          ttl: 300
          dither: false
          payload:
            - type: text
              value: >
                {% if is_state("input_boolean.dishwasher_is_clean", "on") -%}
                  Clean
                {%- else -%}
                  Dirty
                {%- endif %}
              font: ppb.ttf
              x: 178
              "y": 64
              size: 70
              color: red
              anchor: mm
            - type: text
              value: "As of {{ now().strftime('%m/%d/%Y at %I:%M %p') }}"
              font: ppb.ttf
              x: 148
              "y": 110
              size: 15
              color: black
              anchor: mt
            - type: icon
              value: silverware-clean
              x: >
                {% if is_state("input_boolean.dishwasher_is_clean", "on") -%}
                  40
                {%- else -%}
                  50
                {%- endif %}
              "y": 64
              size: 60
              color: black
              anchor: mm
        target:
          entity_id:
            - open_epaper_link.0000021f85043b1c

  - id: 3c66912f-0aa1-469f-9b91-93bfa7c2711f
    alias: Kitchen Light Switch Zigbee Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch: *kitchen_light_switch_device_ids
        config_button:
          - service: cover.toggle
            target:
              entity_id: cover.kitchen_shades
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 170
              level: 50
              effect: Open/Close
              duration: 20 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 70
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a3:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b3:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 130
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_a4:
          - service: light.turn_on
            target:
              area_id: kitchen
            data:
              brightness_pct: 100
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 50
              effect: Medium Rising
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids
        button_b4:
          - service: light.turn_off
            target:
              area_id: kitchen
          - service: script.inovelli_blue_notifications
            data:
              led: All
              color: 142
              level: 10
              effect: Medium Falling
              duration: 15 Seconds
              target:
                device_id:
                  *kitchen_light_switch_device_ids

  - id: ea920c86-437a-4224-8329-7cad4537dc1a
    alias: Manage the Kitchen Shades
    description: Automatically open/close the Kitchen Shades based on the Sun Position
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
        offset: '+1:30:00'
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
    action:
      - choose:
          - alias: If it's after sunset or before sunrise, then close the shade.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: sun
                    before: sunrise
                    before_offset: '+1:30:00'
            sequence:
              - service: cover.close_cover
                target:
                  entity_id: cover.kitchen_shades
          - alias: If it's 90 minutes after sunrise, then open the shade.
            conditions:
              - condition: sun
                after: sunrise
                after_offset: '+1:30:00'
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.kitchen_shades
      - service: script.inovelli_blue_notifications
        data:
          led: All
          color: 170
          level: 50
          effect: Open/Close
          duration: 20 Seconds
          target:
            device_id:
              *kitchen_light_switch_device_ids
    mode: single
