###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  04/14/2020
#  @package      :  Kitchen
#  @description  :  Logic for handling lights in the kitchen.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'kitchen'

    kitchen_light_switch_device_ids: &kitchen_light_switch_device_ids
        - e25098f1e17ab2262e1807b5aa5774ec
        - 3a230c9078dd8ced0fbdbbdff3f649e7

################################################
## Light
################################################
light:

  - platform: group
    name: Kitchen Cabinet Lights
    unique_id: b5d9b202-096a-4fa1-80eb-6d2c4f491374
    entities:
      - light.kitchen_cabinet_lower_lights
      - light.kitchen_cabinet_upper_lights

################################################
## Automation
################################################
automation:
  - id: 47c666bc-1a15-44ee-9712-d9ae472ad785
    alias: Kitchen Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Kitchen.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-switch.yaml
      input:
        zwave_device:
          *kitchen_light_switch_device_ids
        config_button:
          - service: cover.toggle
            target:
              entity_id: cover.kitchen_shades
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 170
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 20
                All LED Strip Effect - Effect: Open/Close
        button_a2:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 70
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium Rise
        button_b2:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 70
                All LED Strip Effect - Level: 10
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium Fall
        button_a3:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              brightness_pct: 100
              kelvin: 3000
              transition: 2
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 130
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium Rise
        button_b3:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_cabinet_lights
            data:
              transition: 2
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 130
                All LED Strip Effect - Level: 10
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium Fall
        button_a4:
          - service: light.turn_on
            target:
              area_id: kitchen
            data:
              brightness_pct: 100
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 142
                All LED Strip Effect - Level: 50
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium Rise
        button_b4:
          - service: light.turn_off
            target:
              area_id: kitchen
          - service: zwave_js.bulk_set_partial_config_parameters
            target:
              device_id:
                *kitchen_light_switch_device_ids
            data:
              parameter: 99
              value:
                All LED Strip Effect - Color: 142
                All LED Strip Effect - Level: 10
                All LED Strip Effect - Duration: 15
                All LED Strip Effect - Effect: Medium Fall

  - id: ea920c86-437a-4224-8329-7cad4537dc1a
    alias: Manage the Kitchen Shades
    description: Automatically open/close the Kitchen Shades based on the Sun Position
    trigger:
      - platform: sun
        event: sunset
      - platform: sun
        event: sunrise
        offset: '+1:30:00'
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
    action:
      - choose:
          - alias: If it's after sunset or before sunrise, then close the shade.
            conditions:
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                  - condition: sun
                    before: sunrise
                    before_offset: '+1:30:00'
            sequence:
              - service: cover.close_cover
                target:
                  entity_id: cover.kitchen_shades
          - alias: If it's 90 minutes after sunrise, then open the shade.
            conditions:
              - condition: sun
                after: sunrise
                after_offset: '+1:30:00'
            sequence:
              - service: cover.open_cover
                target:
                  entity_id: cover.kitchen_shades
      - service: zwave_js.bulk_set_partial_config_parameters
        target:
          device_id:
            *kitchen_light_switch_device_ids
        data:
          parameter: 99
          value:
            All LED Strip Effect - Color: 170
            All LED Strip Effect - Level: 50
            All LED Strip Effect - Duration: 20
            All LED Strip Effect - Effect: Open/Close
    mode: single
