###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  09/01/2018
#  @package      :  Lighting Effects
#  @description  :  Scripts used for various lighting effects
###############################################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'lighting_effects'

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.random_color_loop:
      <<: *customize

    ################################################
    ## Input Select
    ################################################
    input_select.random_color_loop_location:
      <<: *customize

    ################################################
    ## Group
    ################################################
    group.lighting_effects:
      <<: *customize

    ################################################
    ## Light
    ################################################
    light.downstairs_color_lights:
      <<: *customize
      location: Downstairs

    light.upstairs_color_lights:
      <<: *customize
      location: Upstairs

    light.all_color_lights:
      <<: *customize
      location: All

    ################################################
    ## Automation
    ################################################
    automation.start_random_color_loop:
      <<: *customize

    automation.stop_random_color_loop:
      <<: *customize

    ################################################
    ## Script
    ################################################
    script.random_color_loop:
      <<: *customize

    script.random_color_loop_control:
      <<: *customize

################################################
## Input Boolean
################################################
input_boolean:
  random_color_loop:
    name: Color Fade
    initial: off
    icon: mdi:invert-colors

################################################
## Input Select
################################################
input_select:
  random_color_loop_location:
    name: Location
    options:
      - All
      - Downstairs
      - Upstairs
    initial: All
    icon: mdi:radar

################################################
## Group
################################################
group:
  lighting_effects:
    name: Lighting Effects
    control: hidden
    entities:
      - input_select.random_color_loop_location
      - input_boolean.random_color_loop

################################################
## Automation
################################################
automation:

  - id: start_random_color_loop
    alias: Start Random Color Loop
    trigger:
      - platform: state
        entity_id: input_boolean.random_color_loop
        to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: group.downstairs_lights
      - service: script.random_color_loop

  - id: stop_random_color_loop
    alias: Stop Random Color Loop
    trigger:
      - platform: state
        entity_id: input_boolean.random_color_loop
        to: 'off'
    action:
      - service: script.turn_off
        entity_id: script.random_color_loop
      - service: script.turn_off
        entity_id: script.random_color_loop_control
      # Todo store/reset lights affected

################################################
## Script
################################################
script:

  random_color_loop:
    sequence:
      # Pick random color
      - service: light.turn_on
        data_template:
          # This should only evaluate to one lightgroup
          entity_id: >
            {%- for item in states.light if (
              is_state_attr(item.entity_id, 'location', states('input_select.random_color_loop_location'))
              )
            -%}
              {{ item.entity_id }}
            {%- endfor -%}
          rgb_color: ['{{ (range(0, 255) | random) }}','{{ (range(0, 255) | random) }}','{{ (range(0, 255) | random) }}']
          brightness_pct: '{{ (range(0, 100) | random) }}'
          transition: 1.5
      - service: script.turn_off
        entity_id: script.random_color_loop_control
      - delay:
          milliseconds: 750
      - service: script.random_color_loop_control

  random_color_loop_control:
    sequence:
      - service: script.turn_off
        entity_id: script.random_color_loop
      - delay:
          milliseconds: 750
      - service: script.random_color_loop
