###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  07/25/2021
#  @package      :  Master Bathroom
#  @description  :  Controls lights and fans in the Master Bathroom.
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'master_bathroom'

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      master_bathroom_relative_humidity:
        friendly_name: 'Relative Humidity'
        unit_of_measurement: '%'
        value_template: >
          {{ states('sensor.master_bathroom_humidity') | float(0) - states('sensor.upstairs_humidity') | float(0) }}

################################################
## Automation
################################################
automation:
  - id: c9bf0f4b-2f8a-4e9d-a87e-32da42f33608
    alias: Control the Master Bathroom Lights
    description: Utilizes the motion_light blueprint for contolling the Master Bathroom Lights.
    use_blueprint:
      path: rohankapoorcom/motion_light.yaml
      input:
        motion_entity: binary_sensor.master_bathroom_motion
        light_target: light.master_bathroom_lights
        no_motion_wait: 300

  - id: b281c2da-67a2-44b3-a11f-11d763a4ba46
    alias: Control the Master Bathroom Fan
    description: Utilizes motion and humidity for controlling the Master Bathroom Fan.
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: automation_reloaded
      - trigger: state
        entity_id: binary_sensor.master_bathroom_motion
        from: 'off'
        to: 'on'
      - trigger: numeric_state
        entity_id: sensor.master_bathroom_relative_humidity
        above: 20
    actions:
      - choose:
          - alias: If there is motion or high humidity, then turn on the fan.
            conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.master_bathroom_motion
                    state: 'on'
                  - condition: numeric_state
                    entity_id: sensor.master_bathroom_relative_humidity
                    above: 20
            sequence:
              - action: fan.turn_on
                target:
                  entity_id: fan.master_bathroom_fan
              - wait_for_trigger:
                  - trigger: template
                    value_template: >
                      {{ states('sensor.master_bathroom_relative_humidity') | float(0) <= 10
                      and is_state('binary_sensor.master_bathroom_motion', 'off') }}
                continue_on_timeout: false
              - delay:
                  minutes: 5
              - action: fan.turn_off
                target:
                  entity_id: fan.master_bathroom_fan
        default:
          - action: fan.turn_off
            target:
              entity_id: fan.master_bathroom_fan

  - id: e42f4721-966d-4209-b761-b53dcc737935
    alias: Master Bathroom Light Switch Scene Controls
    description: Utilizes a blueprint to handle Scene Controls in the Master Bathroom.
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-switch.yaml
      input:
        inovelli_switch:
          - d80e98e0621de0822a33348e7e141e8b
        config_button:
          - action: switch.toggle
            target:
              entity_id: switch.master_bathroom_towel_warmer

  - id: d3e3e1a3-8235-4ad2-96e7-221d2c989f15
    alias: Notify when the Master Bathroom Towel Warmer is on
    description: Notify when the Master Bathroom Towel Warmer is on
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: switch.master_bathroom_towel_warmer
    actions:
      - choose:
          - alias: If the Towel Warmer is on, set the notification
            conditions:
              - condition: state
                entity_id: switch.master_bathroom_towel_warmer
                state: "on"
            sequence:
              - action: script.inovelli_blue_notifications
                data:
                  led: Led 1
                  color: Red
                  level: 40
                  effect: Pulse
                  duration: Indefinitely
                  target:
                    device_id: d80e98e0621de0822a33348e7e141e8b
        default:
          - action: script.inovelli_blue_notifications
            data:
              led: Led 1
              color: Red
              level: 40
              effect: Clear
              duration: Indefinitely
              target:
                device_id: d80e98e0621de0822a33348e7e141e8b

  - id: f99edeb0-3062-4ba6-9584-a7eca41fef12
    alias: Control the Master Bathroom Towel Warmer
    description: Utilizes a timer to control the Master Bathroom Towel Warmer
    mode: restart
    max_exceeded: silent
    triggers:
      - trigger: homeassistant
        event: start
        id: homeassistant_start
      - trigger: state
        entity_id: switch.master_bathroom_towel_warmer
        from: 'off'
        to: 'on'
        id: master_bathroom_towel_warmer_turned_on
    actions:
      - choose:
          - alias: If Home Assistant just started, turn it off
            conditions:
              - condition: trigger
                id: homeassistant_start
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.master_bathroom_towel_warmer
        default:
          - delay:
              minutes: 90
          - action: switch.turn_off
            target:
              entity_id: switch.master_bathroom_towel_warmer

  - id: 61e51665-413b-4958-8a4f-5a7e29066e60
    alias: Adjust the Master Bathroom Brightness
    description: Utilizes a blueprint to configure the default brightess on the Master Bathroom Lights.
    use_blueprint:
      path: rohankapoorcom/adaptive-lighting-sleep-mode.yaml
      input:
        adaptive_lighting_switch: switch.adaptive_lighting_sleep_mode_master_bathroom
        bedtime: '01:00:00'
        wakeup_time: '08:00:00'
