###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  07/25/2021
#  @package      :  Master Bathroom
#  @description  :  Controls lights and fans in the Master Bathroom.
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'bathroom'


################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      master_bathroom_relative_humidity:
        friendly_name: 'Relative Humidity'
        unit_of_measurement: '%'
        value_template: '{{ states.sensor.master_bathroom_humidity.state|float - states.sensor.master_bedroom_humidity.state|float }}'


################################################
## Automation
################################################
automation:
  - id: c9bf0f4b-2f8a-4e9d-a87e-32da42f33608
    alias: Control the Master Bathroom Lights
    description: Utilizes the motion_light blueprint for contolling the Master Bathroom Lights.
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_entity: binary_sensor.master_bathroom_motion
        light_target:
          entity_id: light.master_bathroom_lights
        no_motion_wait: 300

  - id: b281c2da-67a2-44b3-a11f-11d763a4ba46
    alias: Control the Master Bathroom Fan
    description: Utilizes the bathroom_fan blueprint for controlling the Master Bathroom Fan.
    use_blueprint:
      path: rohankapoorcom/bathroom_fan.yaml
      input:
        motion_entity: binary_sensor.master_bathroom_motion
        relative_humidity_entity: sensor.master_bathroom_relative_humidity
        bathroom_fan_target:
          entity_id: switch.master_bathroom_fan
        relative_humidity_high: 20
        relative_humidity_low: 10
        delay_time: 300