###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/30/2018
#  @package      :  Media / TV
#  @description  :  Integrates lighting and the Harmony Remote for TV/Movies
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'media_tv'

      trigger_roku_keypress: &trigger_roku_keypress
        - platform: event
          event_type: roku_command

      roku_event_data: &roku_event_data
        source_name: 4t8k7RAjE3TBcfheQvCATZ
        type: keypress

media_player:
  - platform: androidtv
    name: Living Room Shield TV
    host: !secret media_player.living_room_shield_tv.host

notify:
  - platform: nfandroidtv
    name: Living Room Shield Tv
    host: !secret media_player.living_room_shield_tv.host

################################################
## Automation
################################################
automation:
  - id: living_room_shield_tv_launch_netflix
    alias: Living Room Shield TV Launch Netflix
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Up
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: Netflix

  - id: living_room_shield_tv_launch_plex
    alias: Living Room Shield TV Launch Plex
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Right
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: Plex

  - id: living_room_shield_tv_launch_youtube
    alias: Living Room Shield TV Launch Youtube
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Down
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: YouTube

  - id: living_room_shield_tv_launch_prime_video
    alias: Living Room Shield TV Launch Prime Video
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Left
    action:
      - service: androidtv.adb_command
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          command: "am start -a android.intent.action.VIEW -d -n com.amazon.amazonvideo.livingroom/com.amazon.ignition.IgnitionActivity"

  - id: living_room_shield_tv_launch_hbo_now
    alias: Living Room Shield TV Launch HBO Now
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Home
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: "com.hbo.hbonow"

  - id: living_room_shield_tv_launch_search
    alias: Living Room Shield TV Launch Search
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Search
    action:
      - service: androidtv.adb_command
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          command: SEARCH

  - id: c8ff656a-e0d6-4b26-9840-0da9863b1867
    alias: Living Room Shield TV Notify Washer
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_wash_completed
        to: 'on'
    action:
      - service: notify.living_room_shield_tv
        data:
          title: Washer Complete
          message: The washer has finished it's cycle.
          data:
            duration: 10
            position: top-right
            transparency: 50%

  - id: e2f38056-ce90-46ca-8138-51a9637e3e50
    alias: Living Room Shield TV Notify Dryer
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_dry_completed
        to: 'on'
    action:
      - service: notify.living_room_shield_tv
        data:
          title: Dryer Complete
          message: The dryer has finished it's cycle.
          data:
            duration: 10
            position: top-right
            transparency: 50%

  - id: c34228e0-c6c9-431f-ad73-cef94537ca2c
    alias: Living Room TV Notify Phone Call
    trigger:
      - platform: state
        entity_id: sensor.line_103_status
        to: 'incoming'
    action:
      - service: notify.living_room_shield_tv
        data_template:
          title: Incoming Phone Call
          message: >
            {{ states('sensor.line_103_caller_name')}} - {{states('sensor.line_103_caller_number') }}
          data:
            duration: 10
            position: top-right
            transparency: 50%