###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/30/2018
#  @package      :  Media / TV
#  @description  :  Integrates lighting and the Harmony Remote for TV/Movies
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'media_tv'


      trigger_roku_keypress: &trigger_roku_keypress
        - platform: event
          event_type: roku_command

      roku_event_data: &roku_event_data
        source_name: 4t8k7RAjE3TBcfheQvCATZ
        type: keypress

media_player:
  - platform: androidtv
    name: Living Room Shield TV
    host: !secret media_player.living_room_shield_tv.host

################################################
## Automation
################################################
automation:
  - id: living_room_shield_tv_launch_netflix
    alias: Living Room Shield TV Launch Netflix
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Up
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: Netflix

  - id: living_room_shield_tv_launch_plex
    alias: Living Room Shield TV Launch Plex
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Right
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: Plex

  - id: living_room_shield_tv_launch_youtube
    alias: Living Room Shield TV Launch Youtube
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Down
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: YouTube

  - id: living_room_shield_tv_launch_prime_video
    alias: Living Room Shield TV Launch Prime Video
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Left
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: "Prime Video"

  - id: living_room_shield_tv_launch_hbo_now
    alias: Living Room Shield TV Launch HBO Now
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Home
    action:
      - service: media_player.select_source
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          source: "com.hbo.hbonow"

  - id: living_room_shield_tv_launch_search
    alias: Living Room Shield TV Launch Search
    trigger:
      - <<: *trigger_roku_keypress
        event_data:
          <<: *roku_event_data
          key: Search
    action:
      - service: androidtv.adb_command
        target:
          entity_id: media_player.living_room_shield_tv
        data:
          command: SEARCH