###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/06/2018
#  @package      :  Media / Music
#  @description  :  Controls the Chromecast Audio devices and integrates them
#                   with Harmony. Speakers power on and off automatically
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'media_music'

      speaker: &speaker
        icon_template: mdi:speaker

      upstairs_speakers_value_template: &upstairs_speakers_value_template
        value_template: "{{ is_state_attr('remote.upstairs_hub', 'current_activity', 'Listen to Music on Speakers') }}"

      downstairs_speakers_value_template: &downstairs_speakers_value_template
        value_template: "{{ is_state_attr('remote.living_room_hub', 'current_activity', 'Listen to Music') }}"

      cover: &cover
        <<: *speaker
        position_template: 50

      decrement_volume: &decrement_volume
        increment: "{{ (states('input_number.volume_increment'))|int }}"

      increment_volume: &increment_volume
        <<: *decrement_volume
        vol_up: true

    input_number.volume_increment:
      <<: *customize

    cover.upstairs_volume:
      <<: *customize
    cover.downstairs_volume:
      <<: *customize

    switch.upstairs_speakers:
      <<: *customize
    switch.downstairs_speakers:
      <<: *customize

    automation.turn_on_speakers_if_chromecast_audio_playing:
      <<: *customize
    automation.turn_off_speakers_when_chromecast_audio_stops_playing:
      <<: *customize
    automation.playpause_chromecast_audio:
      <<: *customize
    automation.rewind_chromecast_audio:
      <<: *customize
    automation.skip_chromecast_audio:
      <<: *customize

    script.harmony_volume:
      <<: *customize
    script.harmony_music_turn_on:
      <<: *customize
    script.turn_off_upstairs_speakers:
      <<: *customize
    script.turn_off_downstairs_speakers:
      <<: *customize

input_number:
  volume_increment:
    name: Increment
    initial: 3
    min: 1
    max: 10
    step: 1
    icon: mdi:volume-high

################################################
## Cover
################################################

cover:
  # Template covers are used to create volume controls
  - platform: template
    covers:

      upstairs_volume:
        <<: *cover
        friendly_name: "Upstairs Volume"
        open_cover:
          service: script.harmony_volume
          data_template:
            <<: *increment_volume
            entity_id: remote.upstairs_hub
        close_cover:
          service: script.harmony_volume
          data_template:
            <<: *decrement_volume
            entity_id: remote.upstairs_hub

      downstairs_volume:
        <<: *cover
        friendly_name: "Downstairs Volume"
        open_cover:
          service: script.harmony_volume
          data_template:
            <<: *increment_volume
            entity_id: remote.living_room_hub
        close_cover:
          service: script.harmony_volume
          data_template:
            <<: *decrement_volume
            entity_id: remote.living_room_hub

switch:
  - platform: template
    switches:

      upstairs_speakers:
        <<: *speaker
        friendly_name: "Upstairs Speakers"
        <<: *upstairs_speakers_value_template
        turn_on:
          service: script.harmony_music_turn_on
          data:
            entity_id: remote.upstairs_hub
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.upstairs_hub

      downstairs_speakers:
        <<: *speaker
        friendly_name: "Downstairs Speakers"
        <<: *downstairs_speakers_value_template
        turn_on:
          service: script.harmony_music_turn_on
          data:
            entity_id: remote.living_room_hub
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.living_room_hub

################################################
## Automation
################################################

automation:

  ################################################
  ## Actions triggered by Chromecast Audio
  ################################################

  - id: turn_on_speakers_if_chromecast_audio_playing
    alias: Turn on Speakers if Chromecast Audio is Playing
    trigger:
      - entity_id: media_player.all_speakers
        platform: state
        to: 'playing'
    action:
      - service: media_player.media_pause
        entity_id: media_player.all_speakers
      - service: script.harmony_music_turn_on
        data_template:
          entity_id: >
            {% if is_state('input_select.last_presence_location', 'Downstairs') %}
              remote.living_room_hub
            {% elif is_state('input_select.last_presence_location', 'Upstairs') %}
              remote.upstairs_hub
            {% endif %}
      - service: automation.turn_off
        entity_id: automation.turn_on_speakers_if_chromecast_audio_playing
      - delay: '00:00:10'
      - service: media_player.media_play
        entity_id: media_player.all_speakers
      - service: automation.turn_on
        entity_id: automation.turn_on_speakers_if_chromecast_audio_playing
    condition:
      - condition: template
        value_template: >
          {% if is_state('input_select.last_presence_location', 'Downstairs') %}
            {% set entity = "remote.living_room_hub" %}
          {% elif is_state('input_select.last_presence_location', 'Upstairs') %}
            {% set entity = "remote.upstairs_hub" %}
          {% endif %}
          {{ is_state(entity, 'off')}}

  - id: turn_off_speakers_when_chromecast_audio_stops_playing
    alias: Turn off Speakers when Chromecast Audio Stops Playing
    trigger:
      - entity_id: media_player.all_speakers
        platform: state
        to: 'off'
        for:
          minutes: 10
      - entity_id: media_player.all_speakers
        platform: state
        to: 'paused'
        for:
          minutes: 10
    action:
      - service: script.turn_off_upstairs_speakers
      - service: script.turn_off_downstairs_speakers
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: media_player.all_speakers
          state: 'off'
        - condition: state
          entity_id: media_player.all_speakers
          state: 'paused'

  ################################################
  ## Actions triggered by Harmony Remote
  ################################################

  - id: playpause_chromecast_audio
    alias: Play/Pause Chromecast Audio
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          roku_usn: 4t8k7RAjE3TBcfheQvCATZ
          type: keypress
          key: Play
    action:
      - service: media_player.media_play_pause
        entity_id: media_player.all_speakers

  - id: rewind_chromecast_audio
    alias: Rewind Chromecast Audio
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          roku_usn: 4t8k7RAjE3TBcfheQvCATZ
          type: keypress
          key: Rev
    action:
      - service: media_player.media_previous_track
        entity_id: media_player.all_speakers

  - id: skip_chromecast_audio
    alias: Skip Chromecast Audio
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          roku_usn: 4t8k7RAjE3TBcfheQvCATZ
          type: keypress
          key: Fwd
    action:
      - service: media_player.media_next_track
        entity_id: media_player.all_speakers

################################################
## Script
################################################

script:

  harmony_volume:
    alias: Harmony Volume Control
    sequence:
      - condition: template
        value_template: "{{ true if is_state(entity_id, 'on') else false }}"
      - service: remote.send_command
        data_template:
          entity_id: "{{ entity_id }}"
          command: "{{ 'VolumeUp' if vol_up else 'VolumeDown' }}"
          device: "{{ 53194709 if entity_id == 'remote.upstairs_hub' else 55995993 }}"
          num_repeats: "{{ increment|int or 3 }}"
          delay_secs: 0.25

  harmony_music_turn_on:
    alias: Turn on Speakers (Music)
    sequence:
      - service: remote.turn_on
        data_template:
          entity_id: "{{ entity_id }}"
          activity: "{{ 32547827 if entity_id == 'remote.upstairs_hub' else 22851881 }}"

  turn_off_upstairs_speakers:
    alias: Turn off Upstairs Speakers
    sequence:
      - condition: template
        <<: *upstairs_speakers_value_template
      - service: remote.turn_off
        entity_id: remote.upstairs_hub

  turn_off_downstairs_speakers:
    alias: Turn off Downstairs Speakers
    sequence:
      - condition: template
        <<: *downstairs_speakers_value_template
      - service: remote.turn_off
        entity_id: remote.living_room_hub
