###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Notifications
#  @description  :  Manages all notification systems (text, voice, etc)
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notifications'

      media_player_notifications: &media_player_notifications
        entity_id: media_player.notifications

      media_player_all_speakers: &media_player_all_speakers
        entity_id: media_player.all_speakers

    automation.keep_notifications_awake:
      <<: *customize

tts:
  platform: google

notify:
  - name: FirebasePush
    platform: html5
    gcm_api_key: !secret notify.gcm_api_key
    gcm_sender_id: !secret notify.gcm_sender_id

################################################
## Automation
################################################
automation:
  # Google homes go to sleep and then make an annoying wake up sound,
  # Now they stay awake
  - id: keep_notifications_awake
    alias: Keep Notifications Awake
    trigger:
      - platform: time
        minutes: '/2'
        seconds: 00
    condition:
      - condition: or
        conditions:
          - condition: state
            <<: *media_player_notifications
            state: 'off'
          - condition: state
            <<: *media_player_notifications
            state: 'idle'
    action:
      - service: media_player.play_media
        <<: *media_player_notifications
        data:
          media_content_id: !secret media_content_id.1second_silence
          media_content_type: audio/mp3

  - id: keep_all_speakers_awake
    alias: Keep All Speakers Awake
    trigger:
      - platform: time
        minutes: '/2'
        seconds: 00
    condition:
      - condition: or
        conditions:
          - condition: state
            <<: *media_player_all_speakers
            state: 'off'
          - condition: state
            <<: *media_player_all_speakers
            state: 'idle'
    action:
      - service: media_player.play_media
        <<: *media_player_all_speakers
        data:
          media_content_id: !secret media_content_id.1second_silence
          media_content_type: audio/mp3
