###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Notifications
#  @description  :  Manages all notification systems (text, voice, etc)
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notifications'

tts:
  platform: google_translate

mailgun:
  domain: !secret mailgun.domain
  api_key: !secret mailgun.api_key

notify:
  - name: FirebasePush
    platform: html5
    vapid_prv_key: !secret notify.gcm.vapid_prv_key
    vapid_pub_key: !secret notify.gcm.vapid_pub_key
    vapid_email: !secret notify.gcm.vapid_email

  - name: rohan_email
    platform: mailgun
    recipient: !secret notify.rohan_email.recipient
    sender: !secret notify.rohan_email.sender
