###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/26/2018
#  @package      :  Notifications
#  @description  :  Manages all notification systems (text, voice, etc)
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'notifications'

tts:
  platform: google_translate

mailgun:
  domain: !secret mailgun.domain
  api_key: !secret mailgun.api_key

notify:
  - name: FirebasePush
    platform: html5
    vapid_prv_key: !secret notify.gcm.vapid_prv_key
    vapid_pub_key: !secret notify.gcm.vapid_pub_key
    vapid_email: !secret notify.gcm.vapid_email

  - name: rohan_email
    platform: mailgun
    recipient: !secret notify.rohan_email.recipient
    sender: !secret notify.rohan_email.sender

automation:

- id: '1665347764581'
  alias: Low Battery Warnings
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - if:
        - condition: template
          value_template: '{{ sensors | length > 0 }}'
        then:
        - service: notify.mobile_app_rohan_s_oneplus_8_pro
          data:
            message: The battery of the sensor(s) {{sensors}} is low.
      exclude:
        entity_id:
        - sensor.office_remote_battery_level
        - sensor.rohan_s_oneplus_8_pro_battery_level