###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  11/28/2020
#  @package      :  Office
#  @description  :  Manages functionality within the office
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'office'

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      office_lights_25_percent:
        friendly_name: Office Lights 25% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 64) }}"

      office_lights_50_percent:
        friendly_name: Office Lights 50% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 129) }}"

      office_lights_75_percent:
        friendly_name: Office Lights 75% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 191) }}"

      office_lights_100_percent:
        friendly_name: Office Lights 100% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 255) }}"

      office_fan_slow:
        friendly_name: Office Fan Set to Slow
        value_template: >
          {{ state_attr('fan.office_fan', 'percentage') > 0 and state_attr('fan.office_fan', 'percentage') <= 52 }}

      office_fan_medium:
        friendly_name: Office Fan Set to Medium
        value_template: >
          {{ state_attr('fan.office_fan', 'percentage') > 52 and state_attr('fan.office_fan', 'percentage') <= 81 }}

      office_fan_high:
        friendly_name: Office Fan Set to High
        value_template: "{{ state_attr('fan.office_fan', 'percentage') > 81 }}"

################################################
## Input Boolean
################################################
input_boolean:
  sentinal_headset_enabled:
    name: Sentinal Headset Enabled
    icon: mdi:headset

################################################
## Light
################################################
light:
  - platform: switch
    name: Office Closet Lights
    entity_id: switch.office_closet_lights

  - platform: template
    lights:
      office_video_lights:
        friendly_name: Office Video Lights
        unique_id: b0ef72e2-eea5-4e16-b71f-793371b1d564
        value_template: >-
          {{ is_state_attr('light.center_key_light', 'brightness', 51)
            and is_state_attr('light.center_key_light', 'color_temp', 143)
            and is_state_attr('light.left_key_light', 'brightness', 38)
            and is_state_attr('light.center_key_light', 'color_temp', 143)
            and is_state_attr('light.office_backlighting', 'brightness', 255)
            and is_state_attr('light.office_backlighting', 'color_temp', 156)
            and is_state('light.office_lights', 'off')
          }}
        turn_on:
          - service: light.turn_on
            entity_id: light.center_key_light
            data:
              color_temp: 143
              brightness: 51
          - service: light.turn_on
            entity_id: light.left_key_light
            data:
              color_temp: 143
              brightness: 38
          - service: light.turn_on
            entity_id: light.office_backlighting
            data:
              color_temp: 156
              brightness: 255
          - service: light.turn_off
            entity_id: light.office_lights
        turn_off:
          - service: light.turn_off
            entity_id: light.center_key_light
          - service: light.turn_off
            entity_id: light.left_key_light
          - service: light.turn_off
            entity_id: light.office_backlighting

mqtt:
  switch:
    - command_topic: "Home/Audio/Office Mixer/Outputs/Office PC Input L/setMute"
      name: Office Ceiling Mic Left
      icon: mdi:microphone
      payload_off: 1
      payload_on: 0
      state_topic: "Home/Audio/Office Mixer/Outputs/Office PC Input L/MUTE"
      unique_id: bbd9f1db-3cd8-460e-9b6b-b86591aff118

    - command_topic: "Home/Audio/Office Mixer/Outputs/Office PC Input R/setMute"
      name: Office Ceiling Mic Right
      icon: mdi:microphone
      payload_off: 1
      payload_on: 0
      state_topic: "Home/Audio/Office Mixer/Outputs/Office PC Input R/MUTE"
      unique_id: 2c2afa34-a4c5-45e4-b4cf-518b022191f5

switch:
  - platform: group
    name: Office Ceiling Mics
    unique_id: B48AD44A_1_2_mute
    entities:
      - switch.office_ceiling_mic_left
      - switch.office_ceiling_mic_right

# switch:
#   - platform: xap_controller
#     path: /dev/xap800
#     name: Office Mixer
#     baud: 57600
#     XAPType: XAP800
#     switches:
#       'Office Ceiling Mics':
#         - "1:1"
#         - "1:2"
#       'Office Speakers':
#         - "1:3"
#         - "1:4"

################################################
## Script
################################################
script:
  set_office_lights_25_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_25_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 25

  set_office_lights_50_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_50_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 50

  set_office_lights_75_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_75_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 75

  set_office_lights_100_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_100_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 100

################################################
## Automation
################################################
automation:
  - id: 0c527fe1-216b-4ace-8e81-004fe00484b9
    alias: Toggle Sentinal Headset
    description: >-
      Switches Sentinal to route voice communication audio over to theJabra Headset
      or the Ceiling Speakers
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.sentinal_headset_enabled
    action:
      - service: switch.turn_on
        target:
          entity_id: >
            {% if trigger.to_state.state == 'on' %}
              switch.sentinal_enable_headset
            {% else %}
              switch.sentinal_enable_speakers
            {% endif %}

  - id: '1649041295671'
    alias: Control Office Closet Lights by Door Sensor
    description: When the Office Closet Door opens, turn on the light; when closed, turn it off.
    trigger:
      - platform: state
        entity_id: binary_sensor.office_closet_door
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_closet_door
                state: 'on'
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.office_closet_lights
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_closet_door
                state: 'off'
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.office_closet_lights
        default: []
    mode: single

  - id: c6888d4f-2471-450d-a8ee-66a68c388169
    alias: Office Lights Scene Controls
    description: Utilizes a blueprint to map track lighting states on the Scene Controller in the Office.
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw31-red-series-switch.yaml
      input:
        zwave_device: bec9907b514903d09df1ba766052f542
        button_b2:
          - service: light.turn_off
            target:
              area_id:
                - office
