###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  11/28/2020
#  @package      :  Office
#  @description  :  Manages functionality within the office
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'office'

################################################
## Binary Sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      streaming_lights_enabled:
        friendly_name: Streaming Lights Enabled
        value_template: >-
          {{ is_state_attr('light.elgato_key_light_dbc2', 'brightness', 51)
            and is_state_attr('light.elgato_key_light_dbc2', 'color_temp', 143)
            and is_state_attr('light.office_lights', 'brightness', 129)
          }}

      office_lights_25_percent:
        friendly_name: Office Lights 25% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 64) }}"

      office_lights_50_percent:
        friendly_name: Office Lights 50% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 129) }}"

      office_lights_75_percent:
        friendly_name: Office Lights 75% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 191) }}"

      office_lights_100_percent:
        friendly_name: Office Lights 100% Enabled
        value_template: "{{ is_state_attr('light.office_lights', 'brightness', 255) }}"

################################################
## Input Boolean
################################################
input_boolean:
  sentinal_headset_enabled:
    name: Sentinal Headset Enabled
    icon: mdi:headset

################################################
## Light
################################################
light:
  - platform: switch
    name: Office Closet Lights
    entity_id: switch.office_closet_lights

################################################
## Script
################################################
script:
  toggle_streaming_lights:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.streaming_lights_enabled
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
              - service: light.turn_off
                entity_id: light.elgato_key_light_dbc2
        default:
          - service: light.turn_on
            data:
              entity_id: light.office_lights
              brightness_pct: 50
          - service: light.turn_on
            entity_id: light.elgato_key_light_dbc2
            data:
              color_temp: 143
              brightness_pct: 20

  set_office_lights_25_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_25_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 25

  set_office_lights_50_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_50_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 50

  set_office_lights_75_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_75_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 75

  set_office_lights_100_percent:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_lights_100_percent
                state: 'on'
            sequence:
              - service: light.turn_off
                entity_id: light.office_lights
        default:
          - service: light.turn_on
            entity_id: light.office_lights
            data:
              brightness_pct: 100

################################################
## Automation
################################################
automation:
  - id: 0c527fe1-216b-4ace-8e81-004fe00484b9
    alias: Toggle Sentinal Headset
    description: >-
      Switches Sentinal to route voice communication audio over to theJabra Headset
      or the Ceiling Speakers
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.sentinal_headset_enabled
    action:
      - service: switch.turn_on
        target:
          entity_id: >
            {% if trigger.to_state.state == 'on' %}
              switch.sentinal_enable_headset
            {% else %}
              switch.sentinal_enable_speakers
            {% endif %}

  - id: '1649041295671'
    alias: Control Office Closet Lights by Door Sensor
    description: When the Office Closet Door opens, turn on the light; when closed, turn it off.
    trigger:
      - platform: state
        entity_id: binary_sensor.office_closet_door
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_closet_door
                state: 'on'
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.office_closet_lights
          - conditions:
              - condition: state
                entity_id: binary_sensor.office_closet_door
                state: 'off'
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.office_closet_lights
        default: []
    mode: single
