###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  08/11/2018
#  @package      :  Presence
#  @description  :  Manages presence detection
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'presence'

    input_select.last_presence_location:
      <<: *customize

    automation.update_last_presence_location_downstairs:
      <<: *customize

    automation.update_last_presence_location_upstairs:
      <<: *customize

input_select:
  last_presence_location:
    name: Last Presence Location
    options:
      - Upstairs
      - Downstairs
    initial: Upstairs
    icon: mdi:radar

################################################
## Automation
################################################

automation:

  - id: update_last_presence_location_downstairs
    alias: Update Last Presence Location (Downstairs)
    trigger:
      - entity_id:
        - binary_sensor.door_window_sensor_158d0001ef6cdb
        - binary_sensor.door_window_sensor_158d000200a9da
        - binary_sensor.motion_sensor_158d0001e07497
        - binary_sensor.motion_sensor_158d0001e0a7db
        platform: state
        to: 'on'
    action:
      - service: input_select.select_option
        entity_id: input_select.last_presence_location
        data:
          option: "Downstairs"

  - id: update_last_presence_location_upstairs
    alias: Update Last Presence Location (Upstairs)
    trigger:
      - entity_id:
        - binary_sensor.door_window_sensor_158d0001b7bb38
        - binary_sensor.door_window_sensor_158d0001de6091
        - binary_sensor.motion_sensor_158d0001e50fb5
        - binary_sensor.motion_sensor_158d0001e51317
        - binary_sensor.motion_sensor_158d0001e05978
        - group.bathroom_motion
        platform: state
        to: 'on'
    action:
      - service: input_select.select_option
        entity_id: input_select.last_presence_location
        data:
          option: "Upstairs"

