###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/14/2018
#  @package      :  Security
#  @description  :  Controls cameras, locks and other security devices
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'security'

    automation.alert_when_front_door_unlocked:
      <<: *customize
    automation.auto_lock_front_door:
      <<: *customize

august:
  login_method: !secret august.login_method
  username: !secret august.username
  password: !secret august.password

zoneminder:
  host: !secret zoneminder.host

camera:
  - platform: zoneminder

amcrest:
  - host: !secret amcrest.host.frontdoor.host
    username: !secret amcrest.host.frontdoor.username
    password: !secret amcrest.host.frontdoor.password
    name: Frontdoor
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected

  - host: !secret amcrest.host.backwindow.host
    username: !secret amcrest.host.backwindow.username
    password: !secret amcrest.host.backwindow.password
    name: Backwindow
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected

  - host: !secret amcrest.host.upstairs.host
    username: !secret amcrest.host.upstairs.username
    password: !secret amcrest.host.upstairs.password
    name: Upstairs
    resolution: high
    stream_source: rtsp
    binary_sensors:
      - motion_detected

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

stream:

group:
  cameras:
    name: Camers
    view: yes
    icon: mdi:cctv
    entities:
      - camera.frontdoor
      - camera.backwindow
      - camera.upstairs


################################################
## Automation
################################################
automation:

  - id: alert_when_front_door_unlocked
    alias: Alert When Front Door Unlocked
    trigger:
    - platform: state
      entity_id: lock.front_door
      from: 'locked'
      to: 'unlocked'
    action:
    - service: tts.google_translate_say
      data:
        entity_id: media_player.notifications
        message: 'Alert - The front door is unlocked'
    - service: notify.firebasepush_oneplus_5t
      data:
        message: 'Alert - Front door unlocked'

  - id: auto_lock_front_door
    alias: Auto Lock Front Door
    trigger:
    - platform: state
      entity_id: lock.front_door
      from: 'locked'
      to: 'unlocked'
      for:
        seconds: 10
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000200a9da
      to: 'off'
      for:
        seconds: 10
    condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d000200a9da
      state: 'off'
    - condition: state
      entity_id: lock.front_door
      state: 'unlocked'
    action:
    - service: tts.google_translate_say
      data:
        entity_id: media_player.notifications
        message: 'Automatically locking the front door'
    - service: lock.lock
      data:
        entity_id: lock.front_door
    - service: notify.firebasepush_oneplus_5t
      data:
        message: 'Front door automatically locked'
