###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/14/2018
#  @package      :  Security
#  @description  :  Controls cameras, locks and other security devices
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'security'

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

stream:

automation:
  - id: d69e14ae-1236-4948-8084-bc162861cbcf
    alias: Show Front Door Lock Status
    description: Utilizes a blueprint to show the Front Door Lock Status on an Inovelli LZW30 Switch
    use_blueprint:
      path: rohankapoorcom/inovelli-vzw31-sn-red-series-lock-notifications.yaml
      input:
        lock_entity: lock.front_door_lock
        zwave_device: 64a4dd14224033fa4119a7b1cb66d888

  - id: ff131bcc-1a3b-4e2f-adf9-4e92eb98260b
    alias: Show Side Door Lock Status
    description: Utilizes a blueprint to show the Side Door Lock Status on an Inovelli LZW30 Switch
    use_blueprint:
      path: rohankapoorcom/inovelli-lzw30-black-series-lock-notifications.yaml
      input:
        lock_entity: lock.side_door_lock
        zwave_device: ae0519b39c8bb3cbe6123a6bb612d2d3

  - id: 96d57252-86bb-44c7-b6b0-926257312296
    alias: Show Garage Door Lock Status
    description: Utilizes a blueprint to show the Garage Door Lock Status on an Inovelli VZM31-SN Dimmer Switch
    use_blueprint:
      path: rohankapoorcom/inovelli-vzm31-sn-blue-series-lock-notifications.yaml
      input:
        lock_entity: lock.garage_door_lock
        inovelli_switch: 1b083dd3571388e94041b98699fb31cf

  - id: 278143dd-38fe-41db-bf51-d54369e3ae32
    alias: Turn on Downstairs Hallway Lights when Garage Door Unlocked
    description: Utilizes a blueprint to turn on the Downstairs Hallway Lights when the Garage Door Lock is Unlocked
    use_blueprint:
      path: rohankapoorcom/lock-light-controls.yaml
      input:
        lock_entity: lock.garage_door_lock
        light_entity: light.downstairs_hallway_lights

  - id: 5879e67e-712b-4770-b2b6-f9b77d5b789c
    alias: Turn on Downstairs Hallway Lights when Side Door Unlocked
    description: Utilizes a blueprint to turn on the Downstairs Hallway Lights when the Side Door Lock is Unlocked
    use_blueprint:
      path: rohankapoorcom/lock-light-controls.yaml
      input:
        lock_entity: lock.side_door_lock
        light_entity: light.downstairs_hallway_lights

  - id: '1652658055419'
    alias: Smoke & CO Alarm Notifications
    description: 'Notify when Smoke or Carbon Monoxide is Detected'
    trigger:
      - type: hot
        platform: device
        device_id: d8822025e42378c2d080639da698f58c
        entity_id: binary_sensor.fire_alarm
        domain: binary_sensor
        id: smoke_detected
      - type: co
        platform: device
        device_id: d8822025e42378c2d080639da698f58c
        entity_id: binary_sensor.co_alarm
        domain: binary_sensor
        id: co_detected
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: smoke_detected
            sequence:
              - service: notify.rohan_kapoor
                data:
                  title: Smoke Alarm Triggered
                  data:
                    channel: Alarm
                    importance: max
                    visibility: public
                  message: The smoke alarm has triggered at Home
          - conditions:
              - condition: trigger
                id: co_detected
            sequence:
              - service: notify.rohan_kapoor
                data:
                  title: Carbon Monoxide Alarm Triggered
                  data:
                    channel: Alarm
                    importance: max
                    visibility: public
                  message: Carbon monoxide has been detected at Home
    mode: single
