###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  05/07/2022
#  @package      :  Server Rack
#  @description  :  Manages functionality within the Server Rack
###############################################################################
---
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'server_rack'

################################################
## Sensor
################################################
sensor:
  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.1.2.1.1.8.1
    unit_of_measurement: "°F"
    name: "UPS Battery Temperature"
    value_template: "{{ value | float(0) / 10.0 }}"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.3.3.1.1.2.2
    unit_of_measurement: "°F"
    name: "UPS EnviroSense Temperature"
    value_template: "{{ value | float(0) / 10.0 }}"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.3.3.2.1.1.2
    unit_of_measurement: "%"
    name: "UPS EnviroSense Humidity"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.2.1.33.1.2.5.0
    unit_of_measurement: "V"
    name: "UPS Battery Voltage"
    value_template: "{{ value | float(0) / 10.0 }}"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.2.1.33.1.2.4.0
    unit_of_measurement: "%"
    name: "UPS Battery Capacity"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.2.1.33.1.2.3.0
    unit_of_measurement: "minutes"
    name: "UPS Runtime Remaining"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.2.1.33.1.3.3.1.3.1
    unit_of_measurement: "V"
    name: "UPS AC Input Voltage"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.2.1.33.1.4.4.1.2.1
    unit_of_measurement: "V"
    name: "UPS Output Voltage"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.1.3.3.2.1.5.1.1
    unit_of_measurement: "%"
    name: "UPS Load"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.1.3.3.2.1.3.1.1
    unit_of_measurement: "A"
    name: "UPS Output Current"
    value_template: "{{ value | float(0) / 100.0 }}"

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.1.3.1.1.1.1.1
    name: "UPS Battery Status"
    value_template: >
          {% if value | int == 1 %}
            Unknown
          {% elif value | int == 2 %}
            Normal
          {% elif value | int == 3 %}
            Battery Low
          {% elif value | int == 4 %}
            Battery Depleted
          {% else %}
            Communication Failure
          {% endif %}

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.1.3.1.2.1.4.1
    name: "UPS Battery Charge Details"
    value_template: >
          {% if value | int == 0 %}
            Float
          {% elif value | int == 1 %}
            Charging
          {% elif value | int == 2 %}
            Resting
          {% elif value | int == 3 %}
            Discharging
          {% elif value | int == 4 %}
            Normal
          {% elif value | int == 5 %}
            Standby
          {% else %}
            Communication Failure
          {% endif %}

  - platform: snmp
    host: !secret snmp.ups.host
    version: 2c
    community: !secret snmp.ups.community
    baseoid: .1.3.6.1.4.1.850.1.1.3.1.3.3.1.1.1.1
    name: "UPS Source"
    value_template: >
          {% if value | int == 0 %}
            Unknown
          {% elif value | int == 1 %}
            Other
          {% elif value | int == 2 %}
            None
          {% elif value | int == 3 %}
            AC Input
          {% elif value | int == 4 %}
            Bypass
          {% elif value | int == 5 %}
            Battery
          {% elif value | int == 6 %}
            Boosting
          {% elif value | int == 7 %}
            Reducing
          {% elif value | int == 8 %}
            Second
          {% elif value | int == 9 %}
            Economy
          {% else %}
            Communication Failure
          {% endif %}

template:
  - sensor:
      - state: >
          {{ ((states('sensor.delta_pro_140012_remain') | as_timestamp - as_timestamp(now())) / 60) | int }}
        unique_id: 44a898ad-76f8-4b4a-8897-2eb7dc2d3e31
        attributes:
          friendly_name: >
            {%- if is_state('binary_sensor.delta_pro_140012_charging', 'on') -%}
              Charge Time
            {%- else -%}
              Runtime
            {%- endif -%}
        unit_of_measurement: "minutes"
        state_class: measurement
      - name: "DELTA Pro 140012 Power Source"
        state: >
          {%- set ac_state = states('sensor.delta_pro_140012_ac_input') -%}
          {%- set dc_state = states('sensor.delta_pro_140012_dc_input') -%}
          {%- if (is_number(ac_state) and ac_state | float > 0)
              and (is_number(dc_state) and dc_state | float > 0) -%}
            AC/DC Input
          {%- elif (is_number(ac_state) and ac_state | float > 0) -%}
            AC Input
          {%- elif (is_number(dc_state) and dc_state | float > 0) -%}
            DC Input
          {%- else -%}
            Battery
          {%- endif -%}
        unique_id: 9cf68e6d-e36e-47cf-a216-99fd474a6e99

rest:
  - resource: !secret rest.ecoflow_river_two_max_api.resource
    scan_interval: 5
    method: GET
    headers: !secret rest.ecoflow_river_two_max_api.headers
    sensor:
      - name: "River 2 Max Battery"
        unique_id: 8f09799f-9de2-41e4-bc62-136d15f267aa
        value_template: "{{ value_json.data.soc }}"
        unit_of_measurement: "%"
        state_class: measurement
        device_class: battery
      - name: "River 2 Max Runtime"
        unique_id: 3707f581-92ab-41d7-9716-fccfdc0912ac
        value_template: "{{ value_json.data.remainTime }}"
        unit_of_measurement: "minutes"
        state_class: measurement
      - name: "River 2 Max Input"
        unique_id: 0e81adf2-987c-48cb-b14f-32bc480676fe
        value_template: "{{ value_json.data.wattsInSum }}"
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
      - name: "River 2 Max Output"
        unique_id: 94456ba8-bd59-4829-983d-a6cc218045ba
        value_template: "{{ value_json.data.wattsOutSum }}"
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
