###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/30/2019
#  @package      :  Vacuum
#  @description  :  Manages integration with Vacuums
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'vacuum'

    ################################################
    ## Vacuum
    ################################################
    vacuum.downstairs_rockrobo:
      <<: *customize
      friendly_name: Downstairs Vacuum

    vacuum.upstairs_rockrobo:
      <<: *customize
      friendly_name: Upstairs Vacuum

    ################################################
    ## Sensor
    ################################################
    sensor.downstairs_roborock_map:
      <<: *customize

    sensor.upstairs_roborock_map:
      <<: *customize

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.send_downstairs_vacuum_home:
      <<: *customize

    input_boolean.send_upstairs_vacuum_home:
      <<: *customize

    ################################################
    ## Script
    ################################################
    script.send_downstairs_vacuum_for_emptying:
      <<: *customize

    ################################################
    ## Automation
    ################################################
    automation.send_downstairs_vacuum_when_kitchen_button_held_down:
      <<: *customize

    automation.send_upstairs_vacuum_when_button_held_down:
      <<: *customize

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "valetudo/downstairs-rockrobo/state"
    json_attributes_topic: "valetudo/downstairs-rockrobo/map_data"
    json_atributes_template: "{{ value | decode_valetudo_map }}"
    name: downstairs_roborock_map
    value_template: 'OK'

  - platform: mqtt
    state_topic: "valetudo/upstairs-rockrobo/state"
    json_attributes_topic: "valetudo/upstairs-rockrobo/map_data"
    json_atributes_template: "{{ value | decode_valetudo_map }}"
    name: upstairs_roborock_map
    value_template: 'OK'


################################################
## Input Boolean
################################################
input_boolean:
  send_downstairs_vacuum_home:
    name: Enabled

  send_upstairs_vacuum_home:
    name: Enabled

################################################
## Script
################################################
script:
  send_downstairs_vacuum_for_emptying:
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: 'vacuum.downstairs_rockrobo'
          command: 'go_to'
          params:
            spot_id: 'Kitchen Trash Can'

  send_upstairs_vacuum_for_emptying:
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: 'vacuum.upstairs_rockrobo'
          command: 'go_to'
          params:
            spot_id: 'Bathroom Trash Can'


################################################
## Automation
################################################
automation:
  - id: send_downstairs_vacuum_when_kitchen_button_held_down
    alias: Send Downstairs Vacuum when Kitchen Button Held Down
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0001e59abe
          click_type: hold
    action:
      - service_template: >
          {% if is_state('input_boolean.send_downstairs_vacuum_home', 'on') %}
            vacuum.return_to_base
          {% else %}
            script.send_downstairs_vacuum_for_emptying
          {% endif %}
        data:
          entity_id: vacuum.downstairs_rockrobo
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.send_downstairs_vacuum_home

  - id: send_upstairs_vacuum_when_button_held_down
    alias: Send Upstairs Vacuum when Button Held Down
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0001e58abe
          click_type: hold
    action:
      - service_template: >
          {% if is_state('input_boolean.send_upstairs_vacuum_home', 'on') %}
            vacuum.return_to_base
          {% else %}
            script.send_upstairs_vacuum_for_emptying
          {% endif %}
        data:
          entity_id: vacuum.upstairs_rockrobo
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.send_upstairs_vacuum_home
