###############################################################################
#  @author       :  Rohan Kapoor
#  @date         :  10/30/2019
#  @package      :  Vacuum
#  @description  :  Manages integration with Vacuums
###############################################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'vacuum'

    ################################################
    ## Vacuum
    ################################################
    vacuum.downstairs_rockrobo:
      <<: *customize
      name: Downstairs Vacuum

    ################################################
    ## Sensor
    ################################################
    sensor.roborock_map:
      <<: *customize

    ################################################
    ## Input Boolean
    ################################################
    input_boolean.send_vacuum_home:
      <<: *customize

    ################################################
    ## Script
    ################################################
    script.send_vacuum_for_emptying:
      <<: *customize

    ################################################
    ## Automation
    ################################################
    automation.send_vacuum_when_kitchen_button_held_down:
      <<: *customize


################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data"
    name: roborock_map
    value_template: 'OK'
    scan_interval: 5


################################################
## Input Boolean
################################################
input_boolean:
  send_vacuum_home:
    name: Enabled

################################################
## Script
################################################
script:
  send_vacuum_for_emptying:
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: 'vacuum.downstairs_rockrobo'
          command: 'go_to'
          params:
            spot_id: 'Kitchen Trash Can'


################################################
## Automation
################################################
automation:
  - id: send_vacuum_when_kitchen_button_held_down
    alias: Send Vacuum when Kitchen Button Held Down
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d0001e59abe
          click_type: hold
    action:
      - service_template: >
          {% if is_state('input_boolean.send_vacuum_home', 'on') %}
            vacuum.return_to_base
          {% else %}
            script.send_vacuum_for_emptying
          {% endif %}
        data:
          entity_id: vacuum.downstairs_rockrobo
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.send_vacuum_home